### ISSUE TITLE
STEP3 Error on Mac

### ISSUE THREAD

**Issue by afbalso** [NLP-Suite/NLP-Suite#1007]
When I type NLP in Terminal on my Mac, I get this error. 

<img width="576" alt="Screenshot 2023-02-04 at 11 04 34 AM" src="https://user-images.githubusercontent.com/122406779/216777520-bc61c506-3beb-4160-aea5-488ae9b8dff0.png">

**Comment by RafaelPiloto10** [comment]
@afbalso, can you open a new terminal and type:
- `cat .zshrc`

Please paste the full results as a comment. Thank you

**Comment by afbalso** [comment]
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/abbybalson/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/abbybalson/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/abbybalson/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/abbybalson/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

alias NLP='conda activate NLP; cd /Users/abbybalson/Desktop/freshmen yr/qtm 190/NLP-Suite-current-stable/setup_Mac/../src/'
(base) abbybalson@Abigails-MacBook-Pro-3 ~ %

**Comment by RafaelPiloto10** [comment]
Open a terminal and type:
- `open -a TextEdit .zshrc`

Edit the last line in the file to this: `alias NLP='conda activate NLP; cd "/Users/abbybalson/Desktop/freshmen yr/qtm 190/NLP-Suite-current-stable/setup_Mac/../src/"'`

Exit the terminal and try again. If all good, feel free to close this issue by clicking the Close Issue button below. Otherwise, upload an attached screenshot of the error
