### ISSUE TITLE
Shape of stories GUI does not run

### ISSUE THREAD

**Issue by christopherli2026** [NLP-Suite/NLP-Suite#1069]
<img width="536" alt="Screenshot 2023-04-11 at 8 08 20 PM" src="https://user-images.githubusercontent.com/123025287/231314774-d93ba3f8-7450-4fe2-8d20-90a10a0f38a6.png">
<img width="1344" alt="Screenshot 2023-04-11 at 8 10 14 PM" src="https://user-images.githubusercontent.com/123025287/231314803-06a7204a-2c0a-4b57-b149-15ab8b1df744.png">

Whenever I press "run", the shape of stories GUI gives me a short message that says that the analysis started. 1 second later, the GUI stops running and does not give any output. No error message pops up either. My computer is a Macbook Air M1 chip.

**Comment by christopherli2026** [comment]
Error in terminal: 
![image](https://user-images.githubusercontent.com/123025287/231316238-7e027eeb-2c39-4aaa-ad3e-95e22a08479b.png)

**Comment by Emory-NLP** [comment]
Christopher, Christopher. Have you read the TIPS? What is wrong with your GUI?

**Comment by christopherli2026** [comment]
Hi Dr. Franzosi, 
Sorry for the confusion! I ran the shape of stories GUI yesterday without any trouble but I forgot to check the input/output configuration again tonight so I put the wrong input. Thanks!

**Comment by Emory-NLP** [comment]
Oh dear. End of the semester fatigue. I will add a check so that it tells you what to do :-)

From: christopherli2026 ***@***.***>
Sent: Tuesday, April 11, 2023 9:18 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] Shape of stories GUI does not run (Issue #1069)


Hi Dr. Franzosi,
Sorry for the confusion! I ran the shape of stories GUI yesterday without any trouble but I forgot to check the input/output configuration again tonight so I put the wrong input. Thanks!

-
