### ISSUE TITLE
[BUG]: AttributeError: 'list' object has no attribute 'shape' Gensim

### ISSUE THREAD

**Issue by atn25** [NLP-Suite/NLP-Suite#1075]
**Add a screenshot of the GUI you are running with the widget selections**
I/O Configuration:
![image](https://user-images.githubusercontent.com/100001530/232242431-16d69d3f-2cbf-4485-bd51-4e1face29ffd.png)
GUI:
![image](https://user-images.githubusercontent.com/100001530/232242487-6a15a4f6-df91-42f6-a47d-7c2ac2667e28.png)
**Describe the bug**
[BUG]: AttributeError: 'list' object has no attribute 'shape' Gensim
**To Reproduce**
Word2Vec with Gensim, plot word vectors 
**Expected behavior**
preparing charts via t-SNE for # distinct words
**Screenshots**

![image](https://user-images.githubusercontent.com/100001530/232235734-5414cc9a-53e4-4a7b-a217-fbf16b5b6e76.png)
**Desktop (please complete the following information):**
Windows 
**Additional context**

**Comment by Emory-NLP** [comment]
Oh dear... please, address all the questions that GitHub asks... "Add a screenshot of the GUI you are running with the widget selections" so that I know what you are running

**Comment by Emory-NLP** [comment]
I need the entire GUI so I see 1. which release you are using; 2. which input you are using...

**Comment by atn25** [comment]
emailed .py, debugged

**Comment by vkameswaran** [comment]
Not sure if this was the solution you also found. I think TSNE was expecting the word vectors to be formatted as a numpy array, rather than a Python list. I think updating `word2vec_Gensim_util` on line 196 should resolve this.

```python
outputFiles = word2vec_tsne_plot_util.run_word2vec_plot(inputFilename, inputDir, outputDir,
                              np.asarray(word_vector_list),
                              filtered_words,
                              vis_menu_var, dim_menu_var)
```

I also ran into an issue with the Three Little Pigs, since the vocabulary size was quite small. ValueError: perplexity must be less than n_samples. I think the default perplexity of 30 was too high when TSNE was initialized in `word2vec_tsne_plot_util`, line 36.

**Comment by Emory-NLP** [comment]
OK, the np change works well even in the older Gensim releases. Not sure about your second comment.

I also ran into an issue with the Three Little Pigs, since the vocabulary size was quite small. ValueError: perplexity must be less than n_samples. I think the default perplexity of 30 was too high when TSNE was initialized in word2vec_tsne_plot_util, line 36.

I get an error with The Three Little Pigs; indeed, the number of words is too small. But the error I get occurs at training the model; it never gets to TSNE. So, not sure where we should test for word sample size and setting it to what value?
