### ISSUE TITLE
[BUG]: Error when creating a word cloud using option "Different colors by POS tags"

### ISSUE THREAD

**Issue by adrianvalencia1** [NLP-Suite/NLP-Suite#1127]
GUI screenshot:
<img width="976" alt="ErrorGui" src="https://github.com/NLP-Suite/NLP-Suite/assets/107940199/9869171f-8ef3-402d-9acf-1a5b360b46aa">

Error when creating a word cloud using the "Different colors by POS tags" option.

**To Reproduce**
1. Go to the word clouds GUI.
2. Select the "Different colors by POS tags" checkbox. (other options untouched)

**Expected behavior**
If no .csv is selected, the option to use POS tags should be disabled.

**Screenshots**
Terminal error log:
<img width="674" alt="Error" src="https://github.com/NLP-Suite/NLP-Suite/assets/107940199/342f5a6a-9134-461f-a9a9-b353c8fe7894">

**Desktop**
 - OS: Windows 10

**Comment by bianshuyang** [comment]
Hi,
Has a wordcloud chart eventually been produced? (You may want to clear all outputs and redo this step to see if a timeline matches). Sometimes some intermediate steps can appear as a bug.

**Comment by adrianvalencia1** [comment]
> Hi, Has a wordcloud chart eventually been produced? (You may want to clear all outputs and redo this step to see if a timeline matches). Sometimes some intermediate steps can appear as a bug.

Hello, no wordcloud chart is produced. I also tried reloading NLP Suite however I still encounter the same issue.

**Comment by bianshuyang** [comment]
I am not sure.... Did you make sure you didn't close anything during the process? You must wait until you can click freely on the GUI, otherwise, it means some running might be in process. Also, make sure you are not running NLP Suite from a zip file. Don't set the output as a zip file.  Don't set the output in a ondrive folder, or any cloud-based location. Don't save the output folder as a virtual address. Don't overcomplicate the output folder. Set the output as simple as possible (such as a real Desktop, etc.) The hunch is that there is something wrong with your output file location. 
Here's a calendly for debug: https://calendly.com/simonbian/nlpinstall?month=2023-09&date=2023-09-07

**Comment by adrianvalencia1** [comment]
> I am not sure.... Did you make sure you didn't close anything during the process? You must wait until you can click freely on the GUI, otherwise, it means some running might be in process. Also, make sure you are not running NLP Suite from a zip file. Don't set the output as a zip file. Don't set the output in a ondrive folder, or any cloud-based location. Don't save the output folder as a virtual address. Don't overcomplicate the output folder. Set the output as simple as possible (such as a real Desktop, etc.) The hunch is that there is something wrong with your output file location. Here's a calendly for debug: https://calendly.com/simonbian/nlpinstall?month=2023-09&date=2023-09-07

The output folder is in a folder on my desktop, so not a .zip file, cloud, etc. I have scheduled a meeting on your Calendly link. Thanks!

**Comment by Emory-NLP** [comment]
Bug fixed. There was a problem in generating the output filename. Will push later today.
See also a potential other problem with wordclouds in Issue Error when generating word cloud #1128.
