### ISSUE TITLE
Error when generating word cloud

### ISSUE THREAD

**Issue by ghost** [NLP-Suite/NLP-Suite#1128]
<img width="1342" alt="Screenshot 2023-09-06 at 8 45 12 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143128568/389afe84-7e50-4c16-a354-3c53d5761b70">

When I try to produce a word cloud, an error in the Terminal comes up saying that the "ImageDraw" object has no attribute "textsize.

**To Reproduce**
1. Go to 'GUI for WordClouds
2. Click on 'Run'
3. Run the program on Terminal

**Screenshots**
<img width="556" alt="Screenshot 2023-09-06 at 8 51 21 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143128568/c2b5b80f-1a3d-4071-8db1-d16f9681000c">

**Comment by Emory-NLP** [comment]
From the following website https://groups.google.com/g/weewx-user/c/4qz0bwgna7g?pli=1 we read:

This is a known problem caused by a change in Pillow, the imaging library used by wordclouds. See what version of Pillow you have by using these two methods. Open terminal. Type activate NLP (then Enter). Then type 
python3 -m pip list -v (or python -m pip list -v)
You will get a long list list, in alphabetical order, of all packages installed in your NLP environment. Scroll up until you find Pillow.
If the Pillow version is 10.0, then this is the problem. The solution is to downgrade your copy of Pillow with the following command:

python3 -m pip install Pillow==9.5.0 (or python -m pip install Pillow==9.5.0)

If it's earlier than 10.0, then it's some other problem.
