### ISSUE TITLE
[BUG]: KeyError: '...' when running Stanza (Generic Issues)

### ISSUE THREAD

**Issue by ZichenHuang000** [NLP-Suite/NLP-Suite#1160]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/34fc717b-75be-410c-8b58-6189590d39c1)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/663689a0-2bd5-43b1-b595-85add50e20d4)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/a4ce9cd0-3623-44d4-a416-1e3aad56a6f0)

DESCRIPTION
I know that there are few similar issues about it, but I am still unable to run Stanza even if I tried the methods. Clicking on "RUN" only gives me this error 

STEPS
1. Go to 'parser and annotator'
2. Set up parser to be Stanza
3. Click RUN

Windows 11
NLP_Suite 3.9.4

**Comment by bianshuyang** [comment]
I am going to set this as the main issue and link the other issues into this page. There has been so many instances of the same nature.

**Comment by bianshuyang** [comment]
These issues are not closed but just merged together.

**Comment by bianshuyang** [comment]
We are using stanza 1.4.2, Some of you are using >=1.5 , which has hbo  meaning ancient hebrew. However, the resources sometimes is still old, so that brings about incompatibility.
To solve:
In **NLP**:
1) Uninstall current stanza: `pip3 uninstall stanza`
2) Install the desired version: `pip install stanza==1.4.2`
3) Remove the "stanza_resources": this folder is in terminal to look up:
First type `python3`
Then type `import stanza`
Then:
`stanza.resources.common.DEFAULT_MODEL_DIR`
Then: go to the folder
Delete or rename to another name that is not "stanza_resources"
Then, close current terminal, go to terminal again, make sure still are in NLP.
`import stanza again`
Then: `stanza.download('en')`

It should be able to solve the problem

**Comment by bianshuyang** [comment]
Just in case you are interested:
https://en.wikipedia.org/wiki/Mokha Mokha is a Yemen language corresponding to myv
https://en.wikipedia.org/wiki/Biblical_Hebrew hbo is Ancient Hebrew, corresponding to hbo
These are new features covered in the newest Stanza uncovered by an older version of Stanza in 1.4.X.
You can compare: https://github.com/stanfordnlp/stanza-resources/tree/main

**Comment by bianshuyang** [comment]
In subsequent run, your pandas might be auto-upgraded. At which point it is beneficial to check the version and downgrade. 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/52821055/ae2cb603-63f3-49d6-869b-c83e031731e2)
To downgrade, simply uninstall by `pip uninstall pandas` and then re install forcing version by `pip install pandas==1.5.2`
Make sure environment as always.
