### ISSUE TITLE
[BUG]: Error in TIPS dictionary lookup, asks to report issue 

### ISSUE THREAD

**Issue by jqian45** [NLP-Suite/NLP-Suite#1161]
I tried to open the DEPREL TIPS file, and this notification came up. I am using the Arabian folktales corpus. 

1. Go to 'NLP & Data Visualization'
 GUI 
2. Open "parsers & annotators" under the analysis tools 
3. Open "TIPS" and scroll down to 'DEPREL'

This error occurred on a MacBook Air OS with release 3.9.7. 
<img width="1440" alt="Screen Shot 2023-09-17 at 8 26 38 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144945114/5655eed5-f1b2-4aec-9370-cfe5e75d2162">

**Comment by bianshuyang** [comment]
We have upgraded to 3.9.8. The problem is solved at that version.
Further, your NLP Suite is not updated to the 3.9.8
Note that the left hand side of the number version is **your** version, but the right is the **new** version.
That means there are somehting wrong with Git set up.
Did you finish the STEP2 command correctly?
