### ISSUE TITLE
Gephi network graphs

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1176]
Network graphs via Gephi can be created by different scripts: SVO_main, CoNLL_table_analyzer, DB_PCACE_data_analyzer_main, data_visualization_main.
The old code worked well for all these scripts except for the data_visualization_main. Contrary to all other scripts, data_visualization_main creates dynamic network graphs NOT using the sentence index as a surrogate for the passing of time - equating the development of sentences one after the other as measured by Sentence ID to a date. data_visualization_main uses a date field to process dynamic network graphs.
The function create_gexf in Gephi_util, unfortunately, no longer works for any of these scripts.

**Comment by bianshuyang** [comment]
[DB_PCACE_data_analyzer_main.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/12734742/DB_PCACE_data_analyzer_main.py.zip)
Fixing the DB PCACE. It turns out that it 's input format incompatibility. (Some columns that is dependent is missing, which has to be enforced to be empty for now to allow for running). Also some minor changes in the Gephi util to allow for correct logic ( a tab is not correctly indented )
[Gephi_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/12734746/Gephi_util.py.zip)

**Comment by Emory-NLP** [comment]
Running it with these options

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/e5964caa-91b7-4fe6-8155-e4a9e3da8aef)

I get this error

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/3d5c86b3-be82-4bad-ac02-b0d02c52c453)

**Comment by bianshuyang** [comment]
Line 1112 is:                 `# % S: 2-digit second(00 - 59)` for me.
If line 1072 is **not**     `print(fileBase, OutputDir, inputFilename, col1, col2, col3, spellCol)` that probably indicate that Gephi wasn't yet replaced to my updates.

**Comment by Emory-NLP** [comment]
Bizarre. I had copied it but not uptopdate. Now working.

**Comment by Emory-NLP** [comment]
Gephi works with DB_PCACE... but not with the SVO algorithm. It produces 0 edges and 0 nodes.

**Comment by bianshuyang** [comment]
[Archive.zip](https://github.com/NLP-Suite/NLP-Suite/files/12739994/Archive.zip)
The SVO algorithm, as it turns out, is that it has some forced Date functions, which never exists in most cases (to use Sentence ID as a date...). In this option, these errors were corrected. Also, a switch logic is applied to preserve the nature of SVO algorithm. The DB ACE will proceed through a special parameter when invoking the gexf
