### ISSUE TITLE
GUI Launch Error

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1228]
0. SCREENSHOTS. 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/3327723b-0a4f-4cd8-858b-5532cf11e5d0)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/788ca77d-d314-4954-8ae9-998778ccb478)
1. DESCRIPTION. 
After updating my NLP Suite, none of the GUIs beyond the NLP_menu_main will open, and instead a long list of errors appears. For example, this is what happens when I attempt to open the Corpus/document(s) statistics GUI.
2. STEPS.
- NLP Main Menu -> Corpus/document(s) statistics
3. INFORMATION.
Windows OS
NLP Suite Release 4.1.8

**Comment by bianshuyang** [comment]
What's your numpy version? mine is 1.24.1
See a duplicated issue:
https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict

**Comment by coralynnkc** [comment]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/c6b52c8d-e7e3-4991-9eb3-de0d41b0a2c4)
This was the original version (1.24.4). 

I pip installed version 1.24.1, but that didn't resolve the issue.

**Comment by bianshuyang** [comment]
OK. https://github.com/spyder-ide/spyder/issues/20409
Looks like an older version might be needed. Numpy deprecated this function a short more while ago
See also https://discuss.tensorflow.org/t/attributeerror-module-numpy-has-no-attribute-typedict/14929
Try numpy version 1.21 as above, and search extensively for web as this issue was a very common one.
Search google: module numpy has no attribute "typedict" 
and try all alternatives suggested as that might be machine / package specific.

**Comment by coralynnkc** [comment]
That worked - thank you so much!
