### ISSUE TITLE
plotly charts in data_visualization_2_main GUI

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1296]
In the data_visualization_2_main GUI

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/d4bc2cdd-b142-44e9-bcc1-8aac4c3c0d4f)

we should introduce a range of chart options available in plotly. The GUI must be redesigned  to allow multiple X and Y axes and special effects. See
[https://plotly.com/python/bar-charts/](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplotly.com%2Fpython%2Fbar-charts%2F&data=05%7C01%7Crfranzo%40emory.edu%7Cdfbf61a4f5bd4ce9903808dbddec1ea9%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638347778439974971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dcRQa8IDQl2oEwNU6uPEeBhna9qT82Ne%2FsDCXmQIXo0%3D&reserved=0)
[https://chart-studio.plotly.com/~etpinard/2080/grouped-bars-on-multiple-axes.py](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchart-studio.plotly.com%2F~etpinard%2F2080%2Fgrouped-bars-on-multiple-axes.py&data=05%7C01%7Crfranzo%40emory.edu%7C32aea7f0e2ad426c1c4a08dbddeb50c9%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638347774984217184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2memm8Y9regA4fN%2BOSUlevca4XtTM9c3FfIoeyrTxC8%3D&reserved=0)

**Comment by bianshuyang** [comment]
[Archive.zip](https://github.com/NLP-Suite/NLP-Suite/files/13315280/Archive.zip)


This involves a lot of file changes, in part because the charts util is so inter-dependent. Key feature involve: when the user select 


<img width="1081" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/3a58050f-69d7-4efe-a673-2076ecaab5f7">
Additional Y-axis, it will process ONLY the field at that line. The "csv file field for visualization" parameter is not passed in for avoiding confusions. 
==
The duplication of selection's withholding is removed, so that when doing the bubble chart, we could better compute. The bubble chart requires 4 field: x axis, y axis, the size of the bubble, and finally the category of the bubble. The x axis and the category fo the bubble could be categorical, however, the y axis and the size of the buble cannot. For now, it is assumed that user could pass in three parameters in the "Select additional part", such that a bubble chart will be computed.

The radar chart is disabled for the multi y axis option, as I could not comprehend the function of multiple y axis in such graph, but it could be added later.

Note: Excel seems to be largely deprecated in the very newest data_visualization_2_main. Nothing has been modified regarding that. Perhaps it could be safer to remove the Excel as an option in this as a whole. 

Bar, line, scatter are all easy to managed by allowing for multiple bars. however, stacked bars should be added as an option to allow for Topic Modeling visualization, etc.

This is a visualization after allowing for bubble chart, exploring the NER of ideology for different presdients:

<img width="1143" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/6e9f6f1e-61b2-4482-9065-08c550a1f889">
