### ISSUE TITLE
Word-searches speed

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1304]
We should speed up the word searches, like for the calculation of n-grams. The searches are VERY slow...

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/3f810631-32ea-40dc-a972-bd84d5301bb1)

**Comment by bianshuyang** [comment]
[file_search_byWord_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/13300368/file_search_byWord_util.py.zip)

**Comment by bianshuyang** [comment]
This speeds up the options from 12 minutes to 4 seconds. However, you must initialize (warm-up the cache) for each different cases as listed below:. That means you have to "warm up" on:

- Search corpus by word (+-K = 0);
- Search corpus by word (+-K !=0 );
- Search corpus by word Extract sentence

Because the way to parse the document is different in each case, so the cache has to be computed differently. 
In the unlikelihood that errors are raised, cache must be deleted in its entirety.
For CGWR, estimated warming phase would be at least 40 minutes for first pass, then future pass takes approx. 10 seconds to complete main search function, but since wordclouds has to be differently computed, at most 2 minutes might be involved.
