### ISSUE TITLE
[BUG]: Indentation Error in SVO_main.py

### ISSUE THREAD

**Issue by jinahyejin** [NLP-Suite/NLP-Suite#211]
I am currently using the AJS corpus. When I tried opening SVO extractor & visualization on the NLP suite, it wouldn't open and instead left me with an error on the command line which shows an indentation error on line 189.

1. Open NLP Suite
2. Click on CORPUS/DOCUMENT Analysis Tools
3. Scroll down to SVO extractor & Visualization and open

![image](https://user-images.githubusercontent.com/59975110/113488890-e4cf7480-948e-11eb-91f9-db60bd3f8a1a.png)

Currently on Windows with the release version type 03-04-2021

**Comment by RafaelPiloto10** [comment]
Hi, could you provide some more information about your set up?
- Windows Version:
- Windows Architecture: 
- Provide a command line screenshot of the following output: `python3 --version`. For this step, please make sure you are in your current environment (NLP for anaconda, etc).

**Comment by Emory-NLP** [comment]
Were you the student who had this problem before with indentation error?

Roberto
Sent from my iPhone

On Apr 3, 2021, at 15:24, jinahyejin ***@***.***> wrote:

﻿

I am currently using the AJS corpus. When I tried opening SVO extractor & visualization on the NLP suite, it wouldn't open and instead left me with an error on the command line which shows an indentation error on line 189.

Steps to reproduce the behavior:

  1.  Open NLP Suite
  2.  Click on CORPUS/DOCUMENT Analysis Tools
  3.  Scroll down to SVO extractor & Visualization and open
  4.  See error

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59975110%2F113488890-e4cf7480-948e-11eb-91f9-db60bd3f8a1a.png&data=04%7C01%7Crfranzo%40emory.edu%7Cd269a2d16f82431e249c08d8f6d61c84%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637530746749674829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xS27m6qmzH%2Fui%2BNGDNRt1PrD9cpF%2FhiBDO1feuneflk%3D&reserved=0>

Currently on Windows with the release version type 03-04-2021

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F211&data=04%7C01%7Crfranzo%40emory.edu%7Cd269a2d16f82431e249c08d8f6d61c84%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637530746749674829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dFTtN8CK%2BlTN7RKXt94mrA2Em%2BtEA%2BJ76i3y3ci%2FoCI%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5YCDAWTHXBIGHJE5DLTG5TPBANCNFSM42KRQ7ZA&data=04%7C01%7Crfranzo%40emory.edu%7Cd269a2d16f82431e249c08d8f6d61c84%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637530746749684825%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gg8f%2FqNcwmnKDt36rVB4dEASypDQpLlm2huzQ4%2Fz7oU%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by jinahyejin** [comment]
Hello. 
My windows version is Windows Home 20H2 and my architecture is 64-bit operating system, x64-based processor. 
Also, the command line of the NLP is blank, but rather the overall command line(?) shows that error. I'm not sure what screenshot to send as everything else is blank and that is the only error I was given.
I didn't have an indentation error before and this is my first time after updating NLP.

**Comment by RafaelPiloto10** [comment]
Please provide a screenshot of the command line after running the following command: `python3 --version`. For this step, please make sure you are in your current environment (NLP for anaconda, etc - you may need to type `nlp` or `conda activate NLP`). You should run this command manually in the command line.

**Comment by jinahyejin** [comment]
> Please provide a screenshot of the command line after running the following command: `python3 --version`. For this step, please make sure you are in your current environment (NLP for anaconda, etc - you may need to type `nlp` or `conda activate NLP`). You should run this command manually in the command line.

![image](https://user-images.githubusercontent.com/59975110/113526829-78856b80-9589-11eb-8d05-453e0c225bd4.png)

It seems that it cannot find my python. I checked my computer and I have both python 3.7 and 3.9. Is there a way let the NLP know I have python?

**Comment by RafaelPiloto10** [comment]
It must have added `python` to path rather than `python3`. Could you instead try running `python --version`.

**Comment by jinahyejin** [comment]
> It must have added `python` to path rather than `python3`. Could you instead try running `python --version`.

This is what I have:

![image](https://user-images.githubusercontent.com/59975110/113529556-b8505100-9591-11eb-973b-f235c47f6ad4.png)

**Comment by Emory-NLP** [comment]
Are you sure you are using the latest version of the NLP Suite?
What your screenshot shows as line 189 (merge_file_option = None) is in line 180 in current_stable.
![image](https://user-images.githubusercontent.com/79026295/113572691-b664ad00-95e6-11eb-8f88-809aeaf250a2.png)

**Comment by jinahyejin** [comment]
> Are you sure you are using the latest version of the NLP Suite?
> What your screenshot shows as line 189 (merge_file_option = None) is in line 180 in current_stable.
> ![image](https://user-images.githubusercontent.com/79026295/113572691-b664ad00-95e6-11eb-8f88-809aeaf250a2.png)

Thank you! I reupdated and its working now.
