### ISSUE TITLE
[BUG]: Sentiment Analysis CSV Output Formatting & Excel

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#212]
**Describe the bug**
The Sentiment Analysis CSV output produces a bug that prevents Excel from properly parsing the CSV file. 

**To Reproduce**
1. Run the Sentiment Analysis tool with the State of the Union Address Corpus (Or any corpus)
2. Review CSV files outputted and excel charts created

**Screenshots**
Example of entry:
<img width="1344" alt="Screen Shot 2021-04-03 at 8 35 50 PM" src="https://user-images.githubusercontent.com/31188361/113495012-2fb3b100-94bc-11eb-8cc1-61893ff4f63c.png">

Example of error during Excel Parsing:
<img width="491" alt="Screen Shot 2021-04-03 at 8 34 37 PM" src="https://user-images.githubusercontent.com/31188361/113495003-0430c680-94bc-11eb-8660-cee242dbecd0.png">

**Desktop (please complete the following information):**
 - OS: OS X (Apple Silicon)
 - Release Version: Most recent pull

**Additional context**
This issue appears to relate to the fact that text is wrapped around `"` twice as seen in the above screenshot.

**Comment by Emory-NLP** [comment]
Which SA algorithm are you running? I do not see an error. Do you have a screenshot of the error in terminal? Thanks!

**Comment by RafaelPiloto10** [comment]
I am running all of them - there is no error. The CSV files are just being created incorrectly it seems like. Excel cannot properly produce the correct data columns as seen in the screenshots.

**Comment by Emory-NLP** [comment]
Oh I see. OK, thanks. Will look into it.

From: Rafael Piloto ***@***.***>
Sent: Saturday, April 3, 2021 8:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Sentiment Analysis CSV Output Formatting & Excel (#212)


I am running all of them - there is no error. The CSV files are just being created incorrectly it seems like. Excel cannot properly produce the correct data columns

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F212%23issuecomment-812949155&data=04%7C01%7Crfranzo%40emory.edu%7C4fedc40ea27d4ee7d20d08d8f7033aa6%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637530940532028190%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4RCzAQcXkjK4LaqIF5XIIOAzr7e%2FdnCSvoVF%2FqSqm%2Fo%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q55D7P7O23VADCUB44TTG6ZKFANCNFSM42KZRXFA&data=04%7C01%7Crfranzo%40emory.edu%7C4fedc40ea27d4ee7d20d08d8f7033aa6%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637530940532038183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rzqKTEyyB41Rp5T9I9hJlL6naoXVXfaTU8F1ySz8nOA%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
