### ISSUE TITLE
[BUG]: Title error about senna "max() arg is an empty sequence"

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#213]
**Describe the bug**
could not run the SVO extractor and always return this error at the beginning

**To Reproduce**
1. Go to 'SVO extractor'
2. Click on 'with coreference' and "normalized date"
3. See error

**Screenshots**
![WechatIMG831](https://user-images.githubusercontent.com/37049722/113499004-c3c95b00-9544-11eb-9baf-280f8d894e20.jpeg)
<img width="255" alt="截屏2021-04-04 下午12 40 36" src="https://user-images.githubusercontent.com/37049722/113499006-c4fa8800-9544-11eb-8fc5-14fa678772da.png">

**Desktop (please complete the following information):**
 - Mac
 - Release Version: most current nlp

**Additional context**

**Comment by RafaelPiloto10** [comment]
Can you attach screenshots of your NLP Window where you have set your input files/directory and output directory. Furthermore, can you attach a screenshot of the files within your input directory if that is what you have selected (please do so in **list** view so that the file extension is visible).

**Comment by chenyingying0402** [comment]
Hi, later I changed a new scr folder and there is no longer such issue. Thanks.
