### ISSUE TITLE
[BUG]: Unable to access Stanford_CoreNLP_OpenIE.jar

### ISSUE THREAD

**Issue by StarLiu1** [NLP-Suite/NLP-Suite#217]
Bug: Unable to use Stanford CoreNLP for SVO
To reproduce: I just ran SVO with the most updated version of NLP Suite
Laptop: OS: 10.15.4

![31617517732_ pic](https://user-images.githubusercontent.com/44296551/113516788-3c7ee600-954a-11eb-8091-5a6930a5ff42.jpg)

**Comment by RafaelPiloto10** [comment]
This is a strange bug due to Apple's Firewall settings. First open your Mac's settings and go to System Preferences, General. Then try running the algorithm again to intentionally trigger this error. Keep an eye on your settings window and you should see that OS X has blocked Stanford CoreNLP OpenIE from running. Prompt OSX to allow it to run and try again.

**Comment by Emory-NLP** [comment]
Also make sure you have the file Stanford_CoreNLP_OpenIE.jar in your NLP/src subfolder. If not, download the Java (jar) files from GitHub at https://github.com/NLP-Suite/NLP-Suite/releases.
