### ISSUE TITLE
name 'createExcelCharts' is not defined

### ISSUE THREAD

**Issue by rbeauvi** [NLP-Suite/NLP-Suite#233]
1. Go to main menu in GUI.
2. Click on shape of stories in the corpus analysis tools.
3. Check the sentiment analysis box (see screenshots for checked boxes).

![Shape of stories terminal error](https://user-images.githubusercontent.com/79262558/114274282-a59fa700-99eb-11eb-811b-f2778cb56049.png)
![Shape of stories menu selections](https://user-images.githubusercontent.com/79262558/114274289-acc6b500-99eb-11eb-8442-17a812fb984f.png)
![Shape of stories too few cvs files](https://user-images.githubusercontent.com/79262558/114274293-b0f2d280-99eb-11eb-8328-7ec8967b5513.png)

 - OS: Windows
 - Release Version 232

Additional notes:
When I tried to used the shape of stories tool without the sentiment analysis box checked, a warning box appeared telling me that 4 csv files were to few for the shape of stories analysis.

**Comment by Emory-NLP** [comment]
The NLP Suite used is out of date. Please, use latest release.

**Comment by rbeauvi** [comment]
I used the latest version yesterday and got the same error....

**Comment by Emory-NLP** [comment]
Roberson, I think there is something fundamentally wrong with the way you pull the latest version of NLP. The line 174 that gives you an error does NOT exist in the current-stable release (I just downloaded and checked to make sure there was nothing wrong with my commit/push via PyCharm). The line that calls the CoreNLP annotator is reported below and it is at 197. Also, please, always report the Release number from NLP_menu so that we know what you are using. You can also check yourself that release number displayed on the GUI against the Latest Release value on GitHub. Do come to office hours tomorrow so that I can take a look at what you are doing and how your NLP src is setup. Roberto

            tempOutputfile=Stanford_CoreNLP_annotator_util.CoreNLP_annotate('', inputDir, outputDir, openOutputFiles, createExcelCharts,'sentiment',False, memory_var)
![image](https://user-images.githubusercontent.com/79026295/114397450-b4619780-9b6c-11eb-933c-f31edcf26314.png)

**Comment by rbeauvi** [comment]
Sure thing.
