### ISSUE TITLE
[BUG]: Indentation Error when opening SVO extractor

### ISSUE THREAD

**Issue by jinahyejin** [NLP-Suite/NLP-Suite#295]
**Describe the bug**
I cannot open the SVO extractor and instead it results in an indentation error in the python file. 

**To Reproduce**
1. Go to SVO extractor
2. Click on Run

**Screenshots**
![image](https://user-images.githubusercontent.com/59975110/117226446-af49de00-ade2-11eb-9655-702525fc0531.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Release Version 1.4.0

**Comment by Emory-NLP** [comment]
Bug fixed

**Comment by Emory-NLP** [comment]
Thank you Jina. Problem fixed and added further options to SVO.

From: jinahyejin ***@***.***>
Sent: Thursday, May 6, 2021 2:45 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Indentation Error when opening SVO extractor (#295)


Describe the bug
I cannot open the SVO extractor and instead it results in an indentation error in the python file.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to SVO extractor
  2.  Click on Run
  3.  See error

Screenshots
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59975110%2F117226446-af49de00-ade2-11eb-9655-702525fc0531.png&data=04%7C01%7Crfranzo%40emory.edu%7C4c720487e4d74678bcf908d91028326f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637558587096535330%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IYnK26JtNNa6Vfss6GEzGh8ZFUZHA9FapXI5c%2F2bO2A%3D&reserved=0>

Desktop (please complete the following information):

  *   OS: Windows 10
  *   Release Version 1.4.0

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F295&data=04%7C01%7Crfranzo%40emory.edu%7C4c720487e4d74678bcf908d91028326f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637558587096545325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bRsgnK68whSuu3AefzLw%2F81%2FGpkBhV2%2B3zMaLo0FGD4%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57Y364U4J2Q2VAXIOLTMHRBHANCNFSM44GASSEA&data=04%7C01%7Crfranzo%40emory.edu%7C4c720487e4d74678bcf908d91028326f%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637558587096555320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3IZ5uWvyoRV42YR9krbCDgeKbx85XSz8EWyOc7S7LDE%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
