### ISSUE TITLE
[BUG]: What's In Your Corpus Error

### ISSUE THREAD

**Issue by tigersun1999** [NLP-Suite/NLP-Suite#323]
There was an error message when I run the what's in your corpus tool.
![53991e72fabe450fa50d837246b3802](https://user-images.githubusercontent.com/62780915/131663476-4c796023-efec-47e0-a14c-0d8d6b3e07d9.png)
And when I followed the instructions in cmd, another error popped off.
![4629baf65ff91e4b05ad972ded2e0bd](https://user-images.githubusercontent.com/62780915/131663533-cba9174c-f406-4f6c-b918-bedc09c3b163.png)
I wonder if there is a way to solve it.

**Comment by Emory-NLP** [comment]
Ehm. Spacy should have been installed by requirements when running STEP 2. I will let Wei answer to you. Sorry! Roberto

From: tigersun1999 ***@***.***>
Sent: Wednesday, September 1, 2021 7:28 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: What's In Your Corpus Error (#323)


There was an error message when I run the what's in your corpus tool.
[53991e72fabe450fa50d837246b3802]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62780915%2F131663476-4c796023-efec-47e0-a14c-0d8d6b3e07d9.png&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941458988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Idnq4o%2BG1ki0nF75RmbkOUwLDbTLik3wyW%2FE2%2FVGDwc%3D&reserved=0>
And when I followed the instructions in cmd, another error popped off.
[4629baf65ff91e4b05ad972ded2e0bd]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62780915%2F131663533-cba9174c-f406-4f6c-b918-bedc09c3b163.png&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941468977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E3LRkaJjQ9NlFJgiFgshpaySsIToeJQa5gxzTynXps4%3D&reserved=0>
I wonder if there is a way to solve it.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F323&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941478971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zjie9II%2FNYiuLy4LTT762Y0MdBltAb%2BQiv6sut9DDdY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57GUCEDBJSFELXBUU3T7YE4ZANCNFSM5DGIEKNA&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941478971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oWe4YDxU%2Bfkut7j6yV5j7wLgtMKE5IEby9CVK6gjBS4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941488968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HZa6PmgNpcLCCjNN9N7xwX%2FH%2FdD2sdcJZNcHqbK098I%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C15a9c4d2679f4432a53b08d96d3b9586%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637660924941498964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mznL37uAzAY2j9vcv7i9wySWF0BYa%2BujQbOxmn6PmIY%3D&reserved=0>.

**Comment by DDVD233** [comment]
Hi Tiger,
Could you run step 2 again and take a screenshot of the output? It looks like it is somewhere in step 2 that the problem occurs.

**Comment by tigersun1999** [comment]
It seems like there was indeed an error message before it said installation completed, but it disappeared so fast I didn't get the screenshot for the entire thing. This is what I got.
![126bebf561b43285e90a4c73af90a38](https://user-images.githubusercontent.com/62780915/131800921-23564959-f12d-4076-8b71-13bd5efbe3c8.png)
![965597247345da89997399bd3d5481a](https://user-images.githubusercontent.com/62780915/131800929-a6f2a96d-545d-4c1c-be78-6caf9222b204.png)

**Comment by RafaelPiloto10** [comment]
@tigersun1999 You must run `conda activate NLP`. That is where spacy was installed -- in the NLP environment. `activate` will only enable the base environment, which does not have spacy. There appears to be some other errors in your most recent screenshots, but it may be worth trying the command again in the correct environment.

Please attach any screenshots when running this command.

**Comment by tigersun1999** [comment]
This is what happens when I run the command under NLP environment
![cc16c301940662b1b38625106a3f69d](https://user-images.githubusercontent.com/62780915/131845557-59b5c905-d4d6-4934-a48f-bf6aca38dc77.png)
![2e5d0fdc70dfbba1bf62525f16e130e](https://user-images.githubusercontent.com/62780915/131845566-9ad71520-d685-4d52-a1ee-4055f9ad542a.png)

**Comment by RafaelPiloto10** [comment]
@tigersun1999, for scientific sake, could you try this in a Command Prompt instead of PowerShell?

**Comment by tigersun1999** [comment]
I think the same stuff happens...
![5b37e4a93d37864aa664470f9a2fdf7](https://user-images.githubusercontent.com/62780915/131846577-a6b4c98b-bf9b-4b9e-8ea4-54a1cdfa3b61.png)

**Comment by RafaelPiloto10** [comment]
@tigersun1999 are you by chance using a VPN or behind a Proxy?

**Comment by tigersun1999** [comment]
Uh I'm pretty sure that I am not

**Comment by RafaelPiloto10** [comment]
Hm, we may need to manually [download](https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-3.1.0) and install it. You will need to follow the instructions found [here](https://github.com/explosion/spaCy/issues/4297#issuecomment-532292152). Ensure that you are in the NLP environment before doing this.

**Comment by DDVD233** [comment]
Yes, this is mostly due to a network error while connecting to Github. As @RafaelPiloto10 said, you can try manually downloading it, or you may try changing your network (i.e. on-campus to off-campus or vise versa). Let us know if it works.

**Comment by DDVD233** [comment]
I learned that you are currently in China. That explains it. The error occurs when the script tries to connect to [raw.githubusercontent.com](https://raw.githubusercontent.com/), which is widely blocked in China. It would be better if you can use a proxy while running this script.

Notice that simply running a VPN/Shadowsocks in the background does not guarantee that you are using that proxy for the Github connection. You have to configure manually. Here is a useful [link](https://stackoverflow.com/questions/31639742/how-to-pass-all-pythons-traffics-through-a-http-proxy). If you need any help, feel free to contact me.

If you are using a router-level proxy, then it will probably work without extra configurations. Examples include Surge under enhanced mode and Openwrt on your router.

**Comment by RafaelPiloto10** [comment]
@tigersun1999, please confirm if the error has been resolved so we can close this issue

**Comment by tigersun1999** [comment]
I was able to manually install spacy through that link, but when I run the ngram tool this popped out.
But when I tried pip install, it said that 
![885de0d55b51ce9bb453dab7c911b8d](https://user-images.githubusercontent.com/62780915/132095720-2eefbf9c-a9f6-4381-876f-8c838bdbaa98.png)

**Comment by DDVD233** [comment]
> I was able to manually install spacy through that link, but when I run the ngram tool this popped out.
> But when I tried pip install, it said that
> ![885de0d55b51ce9bb453dab7c911b8d](https://user-images.githubusercontent.com/62780915/132095720-2eefbf9c-a9f6-4381-876f-8c838bdbaa98.png)

Hi Tiger,
It looks like you have 2 conda environments. One named nlp and the other named NLP (conda environment is case sensitive). Notice that the two are different and the package you installed on one of them cannot be used on the other. 

Please try using `conda activate NLP` instead.

**Comment by tigersun1999** [comment]
Oh I didn't realize that, but the same thing happens when I use NLP instead
![1a28f75bb615ceb3e5fde7a5fa7e1fc](https://user-images.githubusercontent.com/62780915/132097367-6c067173-2074-4825-b4ba-b6fd39925b87.png)

**Comment by DDVD233** [comment]
I think this is a different error. It says it cannot download the required package due to a network error. 
One way to get around this is to refer to the VPN installation [I mentioned earlier](https://github.com/NLP-Suite/NLP-Suite/issues/323#issuecomment-911756668). 

Another way is to download the nltk data manually through [this instruction](https://www.nltk.org/data.html#manual-installation). Please refer to the "Manual installation" part.

Feel free to contact me if you experience any difficulty trying any one of them.

**Comment by Emory-NLP** [comment]
Did you use the CD directory command before activating?

Roberto
Sent from my iPhone

On Sep 4, 2021, at 10:12, tigersun1999 ***@***.***> wrote:

﻿

Oh I didn't realize that, but the same thing happens when I use NLP instead
[1a28f75bb615ceb3e5fde7a5fa7e1fc]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62780915%2F132097367-6c067173-2074-4825-b4ba-b6fd39925b87.png&data=04%7C01%7Crfranzo%40emory.edu%7C24349405de5544f3633908d96fadff86%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663615371865811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C4HGawm1n%2FTvRxDnUbsmTErhinwgo6vE%2BO%2FukMYtRuQ%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F323%23issuecomment-912981041&data=04%7C01%7Crfranzo%40emory.edu%7C24349405de5544f3633908d96fadff86%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663615371865811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gH8%2BtzBSeUzAfiGlOyjbu%2FBEXLk0gRnkX4iKCElnI0o%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q526HSW4FG2ZOBTFARTUAISL5ANCNFSM5DGIEKNA&data=04%7C01%7Crfranzo%40emory.edu%7C24349405de5544f3633908d96fadff86%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663615371875804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BEALMx3Y4PkSyKdKm5tj7ATeWnamBSO6JxZCkFyiDT0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C24349405de5544f3633908d96fadff86%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663615371875804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r%2FgKj597v1csN3lLA46kkGl%2B3u9UFxyLunpUoYEiaNs%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C24349405de5544f3633908d96fadff86%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663615371885800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BIJWbMEvznDwlC%2FFhoVJaODpVCmoRUCmldDU3hoGcqw%3D&reserved=0>.

**Comment by tigersun1999** [comment]
I think it automatically directs to the environment when I activate.
Now I have the two installed, this is what I get from word clouds.
![bc72d2261740336b773b2e6f8b017b7](https://user-images.githubusercontent.com/62780915/132103377-7f4150de-1727-4b33-a6d5-7df9e3e6078d.png)
![9e8c3f698dc9ea4f950df72edc0ccc8](https://user-images.githubusercontent.com/62780915/132103380-d79c4601-2fc6-4e2e-bb51-deef95974a1e.png)
I hope I'm getting closer to correctly installing this stuff :(

**Comment by Emory-NLP** [comment]
Before activating NLP you need to change directory to the NLP directory CD <nlp directory> in terminal. Try that. You probably installed the package in the wrong directory

Roberto
Sent from my iPhone

On Sep 4, 2021, at 09:17, tigersun1999 ***@***.***> wrote:

﻿

I was able to manually install spacy through that link, but when I run the ngram tool this popped out.
But when I tried pip install, it said that
[885de0d55b51ce9bb453dab7c911b8d]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62780915%2F132095720-2eefbf9c-a9f6-4381-876f-8c838bdbaa98.png&data=04%7C01%7Crfranzo%40emory.edu%7Ca29e98a9d26b40d0e21208d96fa649f5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663582263498281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3Rw9Zm%2Fp%2Fl0InM9tkxWRyhr2HM8ybneOYy6e7FDilZE%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F323%23issuecomment-912972945&data=04%7C01%7Crfranzo%40emory.edu%7Ca29e98a9d26b40d0e21208d96fa649f5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663582263508270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vVs6%2FwKwae%2FHBPDyQO4IY%2F0DMtSIhr7pGCvlWEjm3mg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57CT6VQM22VXR2SUK3UAIL5BANCNFSM5DGIEKNA&data=04%7C01%7Crfranzo%40emory.edu%7Ca29e98a9d26b40d0e21208d96fa649f5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663582263518265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0OCh2MKmaUkxPnM3Npy4Xk0ssry6YjqplxZ0UTJhz6E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Ca29e98a9d26b40d0e21208d96fa649f5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663582263518265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OQOTiigloy60tV57mrQiicWoC%2FyY8EIyb%2FYGMHFMETA%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Ca29e98a9d26b40d0e21208d96fa649f5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663582263528262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lAEMYNGkGBzcYY%2BFRwjKToTtC5vNHUvkYq3mjIe2yns%3D&reserved=0>.

**Comment by Emory-NLP** [comment]
The problem was solved with more robust GitHub wiki installation pages on installing packages and being in the right NLP environment.
