### ISSUE TITLE
[BUG]: module "pyLDAvis" missing in the NLP environment

### ISSUE THREAD

**Issue by celinefeng99** [NLP-Suite/NLP-Suite#327]
I think the modules inside anacoda and NLP Suite might reside in different environment in my computer. I have to install "spacy", "pyLDAvis" and other modules manually in terminal even though I have set up the anacoda command. 

Also, when I tried to run the NLP Suite, it does not pop up the next window. The terminal shows that "no module named 'pyLDAvis.gensim'" even after I installed it in the terminal. 

<img width="583" alt="Screen Shot 2021-09-02 at 10 13 02 AM" src="https://user-images.githubusercontent.com/71453334/131860541-9fc5b050-c5cc-427a-b212-00c105e5ed9c.png">

**Comment by DDVD233** [comment]
Could you post a screenshot of how you installed pyLDAvis?

**Comment by celinefeng99** [comment]
I made the command "pip install pyLDAvis" in the terminal.

<img width="573" alt="Screen Shot 2021-09-02 at 10 29 24 AM" src="https://user-images.githubusercontent.com/71453334/131862265-1ec486d1-34d7-49ee-8f62-1d8d40e1e214.png">

**Comment by RafaelPiloto10** [comment]
@celinefeng99, please make sure to activate the NLP environment before running pip install as outlined in the [troubleshooting page](https://github.com/NLP-Suite/NLP-Suite/wiki/Troubleshooting#missing-python-module-or-package).

**Comment by celinefeng99** [comment]
I have solved it, thank you!

**Comment by Emory-NLP** [comment]
Celine, what did you do to solve the issue? You should leave a comment on how you did it. Several students have the same issue. When they pip install a package they do s in the wrong environment. Thanks! Roberto

From: Celine Feng ***@***.***>
Sent: Thursday, September 2, 2021 6:02 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: module "pyLDAvis" missing in the NLP environment (#327)


I have solved it, thank you!

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F327%23issuecomment-912089452&data=04%7C01%7Crfranzo%40emory.edu%7C003b481901a547502dda08d96e5d4609%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637662169161650724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bDCHZSNlAITLT2ryW13wadOFe%2F7Th1d6l3Gw9BIbe0o%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q55J6TL5WPE72EDM6NLT77X5BANCNFSM5DJHQAPA&data=04%7C01%7Crfranzo%40emory.edu%7C003b481901a547502dda08d96e5d4609%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637662169161660715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Czn%2BFCnAGzl%2FW81qGZZRl42mD1b01u6ceDdQWDeEiVM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C003b481901a547502dda08d96e5d4609%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637662169161670710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QheZyPuA9S5PdySVNlp9yuKa%2FssCxorcXQBpZqVPa8Y%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C003b481901a547502dda08d96e5d4609%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637662169161670710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O31W%2B2p2DbrSisqfzooqV0bR6%2Bd4zYouvmtAJN7ob%2Fs%3D&reserved=0>.

**Comment by celinefeng99** [comment]
I was struggling to update the version of NLP Suite, and then I found the "setup_auto_update.command" and solved the problem. The version is now updating automatically. Yet it turned out that while this command is running, my "anaconda.sh" file somehow disappeared. So what I did is basically redo the STEP1 & STEP2 command for it to reinstall the anaconda. The Suite then works.
