### ISSUE TITLE
[Question]: C++ component question

### ISSUE THREAD

**Issue by danielJi030** [NLP-Suite/NLP-Suite#336]
![1630715764(1)](https://user-images.githubusercontent.com/90074893/132076594-8906969f-2588-4ee5-8f53-dcbed26c84d3.png)

Hi. I'm downloading C++ through Visual Studio but don't know which/what components are necessary.

**Comment by Emory-NLP** [comment]
Please look at the troubleshooting pages on GitHub about C++. We will later edit the external software installation pages as well.

Roberto
Sent from my iPhone

On Sep 3, 2021, at 20:37, danielJi030 ***@***.***> wrote:

﻿

[1630715764(1)]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F90074893%2F132076594-8906969f-2588-4ee5-8f53-dcbed26c84d3.png&data=04%7C01%7Crfranzo%40emory.edu%7C18005ddb5bcc4701196408d96f3c3664%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663126667385151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W8Kp2QJmyoKIGhVf0I0SAjWwNKGqAnv10D9OZqdWoeE%3D&reserved=0>

Hi. I'm downloading C++ through Visual Studio but don't know which/what components are necessary.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F336&data=04%7C01%7Crfranzo%40emory.edu%7C18005ddb5bcc4701196408d96f3c3664%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663126667395147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Rt3ySy4tOHQ%2F6NontETzORINIeN1V4HyUfVP%2BGHzRE4%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5Y2JJIFI6SKWFC7XLTUAFS5RANCNFSM5DMWDLFA&data=04%7C01%7Crfranzo%40emory.edu%7C18005ddb5bcc4701196408d96f3c3664%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663126667395147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V3LFIO3nfcIrBs5fiLwOO9SrgBuLN8V%2BoMVj6Pbs7A4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C18005ddb5bcc4701196408d96f3c3664%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663126667405144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=38u7rzFJjWxH9LS%2BSfkfg7x2qTO0OrZMKMJun1chB7M%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C18005ddb5bcc4701196408d96f3c3664%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637663126667415131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y0QHNDYHljxQDqQOQ3EJTZM561GkT5FUcTbwNwSF%2Bg4%3D&reserved=0>.

**Comment by Emory-NLP** [comment]
Problem and solution added to the GitHub wiki pages.
