### ISSUE TITLE
[BUG]: Gensim error when running with 20 topics

### ISSUE THREAD

**Issue by scifinina** [NLP-Suite/NLP-Suite#368]
**Description**
When using Gensim to create a topic model, I am able to successfully get models with 3, 4, and 10 topics. However, when running Gensim with 20 topics I get the error that you can see in the screenshot. I believe a similar error is described under issue #300 

![Screenshot (70)](https://user-images.githubusercontent.com/90849892/133626586-b4f435de-97df-4f3c-88d0-ecf844058247.png)

**To Reproduce**
1. Select topic Modelling with Gensim
2. enter 20 topics into the corresponding field
3. run

**Desktop:** Windows NLP 1.5.4

**Comment by DDVD233** [comment]
I think this is likely a memory issue. What amount of system memory do you have?

You can check by the following steps:
1. Click the windows button.
2. search "task manager"
3. run task manager
4. switch to the performance tab
5. under the memory tab, you can see your installed memory amount.

**Comment by Emory-NLP** [comment]
Looking on the web for the error "TypeError: Object of type 'complex' is not JSON serializable" there is a stackoverflow solution
https://stackoverflow.com/questions/46379763/typeerror-object-of-type-complex-is-not-json-serializable-while-using-pyldavi they point to a solution
I have edited the code and will share before pushing it.

**Comment by scifinina** [comment]
> I think this is likely a memory issue. What amount of system memory do you have?
> 
> You can check by the following steps:
> 
> 1. Click the windows button.
> 2. search "task manager"
> 3. run task manager
> 4. switch to the performance tab
> 5. under the memory tab, you can see your installed memory amount.

I have 16GB memory on my laptop

**Comment by Emory-NLP** [comment]
Nina, did you try the script I sent you? Anyway, the new 1.6.2 release contains the edit I made... and you should re-run the script.

**Comment by scifinina** [comment]
I re-ran Gensim with the new 1.6.2 update and that works fine. Thanks so much!

**Comment by Emory-NLP** [comment]
Wow! At least one good news in a day of dreadful news. Thank you Nina.

From: scifinina ***@***.***>
Sent: Sunday, September 19, 2021 9:19 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Assign ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Gensim error when running with 20 topics (#368)


I re-ran Gensim with the new 1.6.2 update and that works fine. Thanks so much!

-
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F368%23issuecomment-922582853&data=04%7C01%7Crfranzo%40emory.edu%7C03426d035d2a4f1b66f408d97bd491a3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637676975190594590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IInw%2BFN8SC6c8yPy38JdI80t30nKLeokNkcsKZWKhCc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q55I6ZCO6GQLBCAK6BLUC2DWXANCNFSM5EE3BDJA&data=04%7C01%7Crfranzo%40emory.edu%7C03426d035d2a4f1b66f408d97bd491a3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637676975190604583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l6U66FOGYajZqkhKpQr%2Fpll0EOs%2FzZJ0fFU%2B19T%2F9aU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C03426d035d2a4f1b66f408d97bd491a3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637676975190604583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B%2Bt2MoIJrMlmQas5aT2MVkiIM%2F5HDmDr3KGo%2BmJ8NUM%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C03426d035d2a4f1b66f408d97bd491a3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637676975190614570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0RO%2BvsU7KsZLzbRspxBKdEufKy62HB9OuAAq23M%2BDbA%3D&reserved=0>.
