### ISSUE TITLE
[BUG]: Out of Heap Space for only one txt document (Stanford CoreNLP PCFG)

### ISSUE THREAD

**Issue by scifinina** [NLP-Suite/NLP-Suite#377]
**Describe the bug**
After running the Stanford CoreNLP PCFG on one file from my corpus, the program will stop with an error message about "out of memory: heap space"

**To Reproduce**
1. Go to Stanford CoreNLP PCFG
2. settings at 4 memory, nothing else checked.
3. input file, one sample text from corpus
4. Let run for several minutes, until error message appears and stops the program.

![heap overflow error](https://user-images.githubusercontent.com/90849892/134173482-b3ef18ad-2cee-4ca0-811d-6dbe6545304b.png)

**Desktop (please complete the following information):**
Windows with 16gb memory

**Additional context**
Previously resolved Java version problem, am able to run POS annotator within the Stanford CoreNLP window.

**Comment by Emory-NLP** [comment]
By chance, I noticed that -d64 was not recognized in Daniel's machine (Windows). You need to make sure to set your Java to use 64 bits rather than 32, normally set as default in Windows. I have added a reminder in case of problems.
https://www.microfocus.com/documentation/silk-performer/200/en/silkperformer-200-webhelp-en/GUID-12E00376-8056-469B-8585-85B325F6130B.html

**Comment by scifinina** [comment]
My java version is 64 but I noticed the build code after that does not match your canvas message. Is this alright, or how can I change it?

![javaversionscifinina](https://user-images.githubusercontent.com/90849892/134227337-0278d2eb-ef34-4b77-8077-6fc8a0c9a3d1.png)

**Comment by Emory-NLP** [comment]
I see Nina. It is the JAVA initial memory size that is VERY low. Try in command line to
set JAVA_OPTS="Xmx1024M"


From: Nina ***@***.***>
Sent: Tuesday, September 21, 2021 2:32 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Out of Heap Space for only one txt document (Stanford CoreNLP PCFG) (#377)


My java version is 64 but I noticed the build code after that does not match your canvas message. Is this alright, or how can I change it?

[javaversionscifinina]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F90849892%2F134227337-0278d2eb-ef34-4b77-8077-6fc8a0c9a3d1.png&data=04%7C01%7Crfranzo%40emory.edu%7Ca7d5da9f6555493821ab08d97d2e2527%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678459428191595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FWgYgzqsZfFO49qtgZrFny7ipEi6Z%2FDx%2BhpepAXxYHY%3D&reserved=0>

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F377%23issuecomment-924252994&data=04%7C01%7Crfranzo%40emory.edu%7Ca7d5da9f6555493821ab08d97d2e2527%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678459428191595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jt6fZcX%2FuZm3yCupnEevx2qN7X0%2FXq2pzClk1cgpyy8%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q536P3PMSHFXGJE23CLUDDFTHANCNFSM5EOL7ALA&data=04%7C01%7Crfranzo%40emory.edu%7Ca7d5da9f6555493821ab08d97d2e2527%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678459428201586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r6gIG4iuNSUS80rTZe4Q1s%2B3sJG8hiQ5wvWF0HUvDqU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Ca7d5da9f6555493821ab08d97d2e2527%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678459428211586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qum6nWZQnMmrbMiyyu%2Fi41pCONoRAtJlpEcxr3X4ufA%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Ca7d5da9f6555493821ab08d97d2e2527%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678459428211586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bo7rcJAYIRMyRyx76Vc3DTufJwgpBMUNEis51N41onM%3D&reserved=0>.

**Comment by scifinina** [comment]
Now that I have corrected this in my settings, a new java.lang.OutOfMemoryError appears: "GC Overhead limit exceeded"
![Screenshot (80)](https://user-images.githubusercontent.com/90849892/134254398-55dd6e55-52ce-46d3-999c-8a3faff1f1c1.png)

**Comment by Emory-NLP** [comment]
This is a bit beyond my pay grade :-( You could try tech support in the library? I see on the web ways of setting lower and higher limits
set JAVA_OPTS="-Xms128M -Xmx256M"
We reset the max. You could try replacing both values
set JAVA_OPTS="-Xms1024M -Xmx1024M"
But... I am definitely not an expert. Sorry!

From: Nina ***@***.***>
Sent: Tuesday, September 21, 2021 6:10 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Out of Heap Space for only one txt document (Stanford CoreNLP PCFG) (#377)


Now that I have corrected this in my settings, a new java.lang.OutOfMemoryError appears: "GC Overhead limit exceeded"
[Screenshot (80)]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F90849892%2F134254398-55dd6e55-52ce-46d3-999c-8a3faff1f1c1.png&data=04%7C01%7Crfranzo%40emory.edu%7C3d14cb881f2a49bf97d208d97d4c8b28%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678589971736442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Buu7DV6Jm4A1SvsUnA6QJkkGTmqLB3Nag%2BIcm1ipWgo%3D&reserved=0>

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F377%23issuecomment-924424458&data=04%7C01%7Crfranzo%40emory.edu%7C3d14cb881f2a49bf97d208d97d4c8b28%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678589971746432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gxwvFWG%2FVRv0nKYmb0sie%2B%2F7Jj%2B7vMWwnRZSmZNUoL4%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5ZHA74LMTZK7FHGBPLUDD7DHANCNFSM5EOL7ALA&data=04%7C01%7Crfranzo%40emory.edu%7C3d14cb881f2a49bf97d208d97d4c8b28%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678589971756428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WzdLlh711WQ4nv9Ci3h20zBhv9z4KTLqJdzIvz9OzzM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C3d14cb881f2a49bf97d208d97d4c8b28%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678589971756428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GJfPJaRPaRKYkec5USxulXIgDkFMMq750w9FIZWUsoY%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C3d14cb881f2a49bf97d208d97d4c8b28%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637678589971766423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H2wnMacJbVkf%2FuPZ%2Fl4xdZFRPZnIWpOuhl5OZ1LVFhQ%3D&reserved=0>.
