### ISSUE TITLE
[BUG]: NLP Suite suddenly not working

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#385]
I had been trying to run Stanford CoreNLP again and decided to close it after it had been running for about 24 hours. When I tried to open the NLP Suite again, I got this message, and the NLP Suite would not open.
![Image 9-22-21 at 9 01 PM](https://user-images.githubusercontent.com/78457469/134440983-5b725e8e-858d-4e8a-81bd-d7497ff428b6.jpg)

**Comment by Emory-NLP** [comment]
Ehm. So sorry Allison. Very weird errors. Let’s talk tomorrow Allison. Try to reboot your machine and see if that helps. Sorry!

Roberto
Sent from my iPhone

On Sep 22, 2021, at 21:02, allisonreinhardt ***@***.***> wrote:

﻿

I had been trying to run Stanford CoreNLP again and decided to close it after it had been running for about 24 hours. When I tried to open the NLP Suite again, I got this message, and the NLP Suite would not open.
[Image 9-22-21 at 9 01 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78457469%2F134440983-5b725e8e-858d-4e8a-81bd-d7497ff428b6.jpg&data=04%7C01%7Crfranzo%40emory.edu%7C947a688f800f4a1affbf08d97e2dd29d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637679557548903137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B48Y%2FTUdT1rpsFzsZu456gEjI%2F04YvQKdmRCs%2FIku7Y%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F385&data=04%7C01%7Crfranzo%40emory.edu%7C947a688f800f4a1affbf08d97e2dd29d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637679557548903137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m4aRgq0XM9ypEcrUIO67ao3GwohIeWKYybw31MNuVnY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56YTJSPTRTV43ALSO3UDJ4CPANCNFSM5ESSFCCA&data=04%7C01%7Crfranzo%40emory.edu%7C947a688f800f4a1affbf08d97e2dd29d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637679557548913133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PyQbSWcWRiQ2TTfq6ziLfsu%2FJz0u3%2BrRfZEgXaxh%2FO4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C947a688f800f4a1affbf08d97e2dd29d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637679557548923128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GTfsAmbnfPAShP1fbpdXV%2FUXgzrh7CvYu9AHLq8SGkw%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C947a688f800f4a1affbf08d97e2dd29d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637679557548923128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JT80XE%2B0DRFOg6bgNVkRysZ0H1JTWqxuUIpQg5CYbcA%3D&reserved=0>.

**Comment by Emory-NLP** [comment]
The problem with circular reference has now been solved.
