### ISSUE TITLE
[BUG]: Gender Annotator fails to produce CSV file

### ISSUE THREAD

**Issue by FF15enc** [NLP-Suite/NLP-Suite#391]
**Describe the bug**
Harry Potter Corpus after running Gender Annotator produces TypeError: string indices must be integers

**To Reproduce**
Steps to reprodu
Gender Annotator with the following settings. 
<img width="1146" alt="Screen Shot 2021-09-24 at 5 10 38 PM" src="https://user-images.githubusercontent.com/78893139/134740100-90c7bfdb-de4e-4d36-b3c1-7c5e5a1c09da.png">
ce the behavior:

**Screenshots**
<img width="712" alt="Screen Shot 2021-09-24 at 5 16 28 PM" src="https://user-images.githubusercontent.com/78893139/134740609-d794cd52-9ae7-475a-a919-d1f03bc4e0b7.png">
<img width="571" alt="Screen Shot 2021-09-24 at 5 12 34 PM" src="https://user-images.githubusercontent.com/78893139/134740258-5b3cc070-9284-4022-bf8d-53a021b4e114.png">
<img width="569" alt="Screen Shot 2021-09-24 at 5 11 47 PM" src="https://user-images.githubusercontent.com/78893139/134740195-1e90537a-bc00-45db-9cc0-6d668711c70f.png">

**Desktop (please complete the following information):**
OSX, NLP 1.6.8, Java JDK 17

**Additional context**
The entire process finishes and the file converts to JSON file. However, it fails to produce any csv files.

**Comment by Emory-NLP** [comment]
Chris! You are using release version 1.6.2. We are on 1.6.8.

From: Chris Feng ***@***.***>
Sent: Friday, September 24, 2021 5:17 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Title (#391)


Describe the bug
Harry Potter Corpus after running Gender Annotator produces TypeError: string indices must be integers

To Reproduce
Steps to reprodu
Gender Annotator with the following settings.
[Screen Shot 2021-09-24 at 5 10 38 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78893139%2F134740100-90c7bfdb-de4e-4d36-b3c1-7c5e5a1c09da.png&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487119620%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x9N8WpzJmvDf1eSOo%2BhmK0Mwi6%2BHsR1VdcgbjJ88GuM%3D&reserved=0>
ce the behavior:

Screenshots
[Screen Shot 2021-09-24 at 5 16 28 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78893139%2F134740609-d794cd52-9ae7-475a-a919-d1f03bc4e0b7.png&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487129616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Masz9hnomQfWCSRDhuHlVgYTYFSRr82FrF%2F6GkmYqg%3D&reserved=0>
[Screen Shot 2021-09-24 at 5 12 34 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78893139%2F134740258-5b3cc070-9284-4022-bf8d-53a021b4e114.png&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487129616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7p653733DvOmIFX2ToFAeR5Gdb2YzR2fd%2Fz3ubK0jtM%3D&reserved=0>
[Screen Shot 2021-09-24 at 5 11 47 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78893139%2F134740195-1e90537a-bc00-45db-9cc0-6d668711c70f.png&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487139614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=io3Hn6mPpKdYQv64nEZHPY318XzmGgpu8OycYYi0v5I%3D&reserved=0>

Desktop (please complete the following information):
OSX, NLP 1.6.8, Java JDK 17

Additional context
The entire process finishes and the file converts to JSON file. However, it fails to produce any csv files.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F391&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487139614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3CTiAN29IbIllIHtnkYqf%2Bq%2F3DKOrcP9847oONNPLuY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57KTF4FWRWHZ23XASLUDTTGNANCNFSM5EWYEAFQ&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487149604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pixjl5ygTtzG6bpt0g6lETlCheLqdEVli7q4qAhBF%2FQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487159600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G%2FtuJx%2BXrNPRhvIZFfapVMFGKRw%2B4n2as%2B7HWph4a90%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C5453e94ad0a243fea14808d97fa0b5bd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637681150487159600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ijQGtqMt11QC7sm%2BnJ%2BN8eMvTN5Nth8BGbPCTM0wKZQ%3D&reserved=0>.
