### ISSUE TITLE
[BUG]: Stanford Core NLP fails to output files

### ISSUE THREAD

**Issue by ryan-anil** [NLP-Suite/NLP-Suite#395]
I fixed the previous issues I was having with Java JDK 8 but now when I try to run the Stanford Core NLP I get this error for each file that I try to use the parser on. Everything seems to run fine for each file, however, an error occurs when outputting something in JSON. It also shows a timeout error, which is odd because I don't think I would be running out of memory if it ran properly.
![Screenshot (15)](https://user-images.githubusercontent.com/89484984/134821714-a784dcd1-c992-46a2-a4d0-7a80f2bf7853.png)

**Comment by Emory-NLP** [comment]
I think we need to Zoom to see what is going on. Time now? I teach at 4...

**Comment by ryan-anil** [comment]
I am able to now. Should I join our normal class link or something else?

**Comment by Emory-NLP** [comment]
Office hours link

From: ryan-anil ***@***.***>
Sent: Tuesday, September 28, 2021 3:18 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Stanford Core NLP fails to output files (#395)


I am able to now. Should I join our normal class link or something else?

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F395%23issuecomment-929551215&data=04%7C01%7Crfranzo%40emory.edu%7Cf3dc52f9ccf94cc63df408d982b4aaaa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684534741312427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kFZEgH5JS9a1LYa%2FxTPYAOZR568qjFg9fji9MD7L1LE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57WYAW4JFTF2EUUOYDUEIIF5ANCNFSM5EZDPIFQ&data=04%7C01%7Crfranzo%40emory.edu%7Cf3dc52f9ccf94cc63df408d982b4aaaa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684534741312427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T7CDeKWfEtidJRo1z%2BVmmx3TucGrnQKD3wYVdFJGk9k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Cf3dc52f9ccf94cc63df408d982b4aaaa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684534741322418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iBOEg1QcTa0%2FNAqZIPSOG0e2NV%2FUGAbF%2BZAIS3FYjdE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Cf3dc52f9ccf94cc63df408d982b4aaaa%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684534741332415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iCFv9%2F%2FVARC%2BxKeUd%2FmJunjoGqPezeQSC82%2F2l6lsUU%3D&reserved=0>.
