### ISSUE TITLE
[BUG]: Stanford CoreNLP GUI Does not Open in 1.7.1+ Version

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#404]
**Describe the bug**
After upgrading to version 1.7.1+, the Stanford CoreNLP GUI no longer opens from the main NLP Suite GUI.  This was not an issue in version 1.7.0.

**To Reproduce**
1. Upgrade to version 1.7.1+
2. Select the desired input/output files
3. Select 'Stanford CoreNLP as the external software and the CORPUS/DOCUMENT Analysis Tool
4. The script runs, but encounters a syntax error

**Screenshots**
<img width="568" alt="Screen Shot 2021-09-28 at 6 26 36 PM" src="https://user-images.githubusercontent.com/89608553/135174180-f7f205b2-2ac5-4d3d-8cee-8640749a8b99.png">

**Desktop (please complete the following information):**
 - OS: Big Sur 11.5.2
 - Release Version NLP Suite Version 1.7.1+

**Comment by Emory-NLP** [comment]
and is missing. When I get home will push the change

Roberto
Sent from my iPhone

On Sep 28, 2021, at 18:28, BillyMartin8 ***@***.***> wrote:

﻿

Describe the bug
After upgrading to version 1.7.1+, the Stanford CoreNLP GUI no longer opens from the main NLP Suite GUI. This was not an issue in version 1.7.0.

To Reproduce
Steps to reproduce the behavior:

  1.  Upgrade to version 1.7.1+
  2.  Select the desired input/output files
  3.  Select 'Stanford CoreNLP as the external software and the CORPUS/DOCUMENT Analysis Tool
  4.  The script runs, but encounters a syntax error

Screenshots
[Screen Shot 2021-09-28 at 6 26 36 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89608553%2F135174180-f7f205b2-2ac5-4d3d-8cee-8640749a8b99.png&data=04%7C01%7Crfranzo%40emory.edu%7Cb06a6f026b1a408c894b08d982cf4966%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684649070774509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cfsBYmCg9%2BKzPWdny2kpyyIGGRwb86z83E%2FiEtjI7AI%3D&reserved=0>

Desktop (please complete the following information):

  *   OS: Big Sur 11.5.2
  *   Release Version NLP Suite Version 1.7.1+

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F404&data=04%7C01%7Crfranzo%40emory.edu%7Cb06a6f026b1a408c894b08d982cf4966%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684649070784506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T1GiSoLv%2FaZ4wAQ95jIgSxFemIN3tWVOKubdDhCJ2lU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q52ZQBEZC5O3OX4A4P3UEI6QRANCNFSM5E6OVQPQ&data=04%7C01%7Crfranzo%40emory.edu%7Cb06a6f026b1a408c894b08d982cf4966%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684649070784506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2Erz4uJEBn1UZ32t7GZ48supsNWROD2uU6c%2Fz6Aot0Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Cb06a6f026b1a408c894b08d982cf4966%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684649070794532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ozah5ygy51BJjsZC349B8PqukD%2BWSK9qcB1ll8cSgwE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Cb06a6f026b1a408c894b08d982cf4966%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637684649070794532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GZsbz76Fz5uf4Jh69RUy%2BHZDjxeTeLmrQ8AcUMHuz0s%3D&reserved=0>.
