### ISSUE TITLE
[BUG]: Key Error: "Location" and Tkinter exception

### ISSUE THREAD

**Issue by ryan-anil** [NLP-Suite/NLP-Suite#416]
I'm trying to use geocoding but keep getting an error before any algorithm starts. I'm using a csv file with NER LOCATION tags as the input.
![Screenshot (21)](https://user-images.githubusercontent.com/89484984/135770700-f177dbaa-32b2-4729-8cbf-49e74c0575ec.png)
![Screenshot (20)](https://user-images.githubusercontent.com/89484984/135770703-149535c3-d7a4-4278-a990-482587601057.png)

The key error just says "Location", I'm not sure what that means at all.

**Comment by Emory-NLP** [comment]
Do you have time to Zoom? I do not get that error but it all depends upon the files you are using. Could you send me to my email the csv file displayed in the GUI? I can try that and perhaps then meet

From: ryan-anil ***@***.***>
Sent: Sunday, October 3, 2021 4:37 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Title (#416)


I'm trying to use geocoding but keep getting an error before any algorithm starts. I'm using a csv file with NER LOCATION tags as the input.
[Screenshot (21)]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89484984%2F135770700-f177dbaa-32b2-4729-8cbf-49e74c0575ec.png&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012664116%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JGlUaIzPvMj0ANMmyUQIXfzr1I0%2Ba8JHDjc%2B%2BNTNLC0%3D&reserved=0>
[Screenshot (20)]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89484984%2F135770703-149535c3-d7a4-4278-a990-482587601057.png&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012674112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k4N9So6lxnHvtkvjaY8qMWaiTQYVJHGiXoT0NDk1s%2B8%3D&reserved=0>

The key error just says "Location", I'm not sure what that means at all.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F416&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012674112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qsEQPhHndPJssTgf6N9HHfMrGCge4saj4Yq6N92HCLk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56Y5RCPHSZICJLAXZTUFC5FPANCNFSM5FH7WNAQ&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012684107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=llUGNtA%2FK3Sht0%2FyL9pkcx2EkysDZn4NK4EvU%2FlZMu4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012684107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xYLf6stNptBuzb0mXD9b4xTc%2Fv9G3Vx6V1LkiwC202w%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Cfe209adc40c84a304cba08d986ad80c5%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688902012694106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QI81FTbIMgq2CwzTMswPw%2FlBDybLVD%2Bm6TbJiM%2Fgah8%3D&reserved=0>.

**Comment by ryan-anil** [comment]
I am able to Zoom and I just sent you the csv file I used.

**Comment by ryan-anil** [comment]
The error persists regardless of the selected Geocoder Service and Software. I have tested it with Nominatim and the Google Maps geocoder as well as the Google Earth Pro and Google Maps software selected.

**Comment by Emory-NLP** [comment]
OK, I get the same error with your file. Let me try to fix it

From: ryan-anil ***@***.***>
Sent: Sunday, October 3, 2021 5:13 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Key Error: "Location" and Tkinter exception (#416)


The error persists regardless of the selected Geocoder Service and Software. I have tested it with Nominatim and the Google Maps geocoder as well as the Google Earth Pro and Google Maps software selected.

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F416%23issuecomment-933026452&data=04%7C01%7Crfranzo%40emory.edu%7C100fdff876c648b8c47308d986b28937%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688923635671359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=98GIRctqpMhj%2B%2BBoGfOFUzCE58SIvbFosebLV8qo%2BnE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5YTIRVWHDCW6AP6HHLUFDBMRANCNFSM5FH7WNAQ&data=04%7C01%7Crfranzo%40emory.edu%7C100fdff876c648b8c47308d986b28937%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688923635681348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lGKXOdPXSKkrlE0YLR%2FiOeXuFfMacjTvEIiARUbkhwg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C100fdff876c648b8c47308d986b28937%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688923635691342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=veTeZs5xUm%2FVD1UkecCmGeOtxURh%2BJggs9u1vowuqjE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C100fdff876c648b8c47308d986b28937%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637688923635691342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sjOy6mSk9mGHNWEg%2BkFoIC4PgyIonvEoWZave8RpHBE%3D&reserved=0>.
