### ISSUE TITLE
[BUG]: Error in Geographic Maps: Google Earth Pro

### ISSUE THREAD

**Issue by emmaej13** [NLP-Suite/NLP-Suite#422]
Looks like it is making an error while reading the input file. Attached is the error message, the GUI, and the input file:

![image](https://user-images.githubusercontent.com/78837632/135778206-cb9cd930-fff1-4fd4-9bc5-33114f776526.png)

![image](https://user-images.githubusercontent.com/78837632/135778160-794b7cec-acc0-467f-abb0-3c5b08c482c7.png)

Input file:
[locations.csv](https://github.com/NLP-Suite/NLP-Suite/files/7274763/locations.csv)

**Comment by Emory-NLP** [comment]
Please, try the the 1.7.5 release. It should have taken care of the problem

**Comment by emmaej13** [comment]
Just updated to 1.7.5 and ran again. Got the same error

**Comment by emmaej13** [comment]
Also, I removed all the blank rows from my input file

**Comment by Emory-NLP** [comment]
Works just fine on my end...

From: emmaej13 ***@***.***>
Sent: Sunday, October 3, 2021 8:15 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Error in Geographic Maps: Google Earth Pro (#422)


Looks like it is making an error while reading the input file. Attached is the error message, the GUI, and the input file:

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78837632%2F135778206-cb9cd930-fff1-4fd4-9bc5-33114f776526.png&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738674977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z%2BLnG1CDAmpIkn03YqYemw9b6zQ9nVQBfZGIvCCgHBo%3D&reserved=0>

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78837632%2F135778160-794b7cec-acc0-467f-abb0-3c5b08c482c7.png&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738684974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C47Y4lA70oOtCCPJswI6mzWCecY9fM09s%2Br0pCu4Dpw%3D&reserved=0>

Input file:
locations.csv<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Ffiles%2F7274763%2Flocations.csv&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738684974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9uTW%2FwUdPksm78VbYCdrRSMegy7Fgz9BOwbrR1gTE0s%3D&reserved=0>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F422&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738694977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e%2Fis5Sy36yVY8aMSN4glbY%2FTFLnWYXBlIKjg%2FADqRJs%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56NOH6IAT4WKBTWZ3LUFDWWNANCNFSM5FIFRFAQ&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738694977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Of3HI9q5v0nnC1Bc9Lm6X1sjdSupvQ5VDbj3BLSbDtE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738704970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=07yOHzNMP67ImW0wcGOZEKXwZfY8Vvt%2F%2Fec%2FnZV8H0I%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C7a029006e0104d668fe008d986cbf03c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637689032738714965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EKvoKPuGzBN9p04g2pYK5WBcqHETlRjta8HZZ2NTqGY%3D&reserved=0>.

**Comment by emmaej13** [comment]
Ok, good to know that there probably isn't anything wrong with the file itself. Any ideas as to what might be the issue on my end?

**Comment by ryan-anil** [comment]
I am getting the same error as Emma. I have been trying input files with differing amounts of lines. Even with just one line of data, the error occurs. I don't think it relates to the files.

**Comment by Emory-NLP** [comment]
Oh, now I see a different GUI. And I get the same error with this one. Let me take a look at this.

**Comment by meganxyang** [comment]
I got the same error as Emma and as Ryan brought up earlier today
<img width="1239" alt="Screen Shot 2021-10-03 at 9 18 45 PM" src="https://user-images.githubusercontent.com/44277925/135783912-c5131eb7-faac-46ad-875d-316e7e8ac480.png">

<img width="674" alt="Screen Shot 2021-10-03 at 6 31 14 PM" src="https://user-images.githubusercontent.com/44277925/135783925-071d289b-c761-4d05-a1b4-d45125abe3a8.png">

**Comment by Emory-NLP** [comment]
Hopefully the GIS Google Earth Pro script (not GIS script) will now work. The code was breaking on my end as well with your csv file.

**Comment by Emory-NLP** [comment]
Problem should be solved.
