### ISSUE TITLE
[BUG]: Visualizations in Gephi

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#447]
**Describe the bug**
Trying to open an SVO output in Gephi via the NLP Suite generates an error.

**To Reproduce**
1. Open NLP Suite
2. Under visualization tools, go to Network Graphs
3. Select the Gephi network graph check box

**Screenshots**
<img width="1050" alt="Screen Shot 2021-10-17 at 1 23 35 PM" src="https://user-images.githubusercontent.com/31188361/137638121-3015deae-e6d2-4e94-99b4-585f7ddceaa3.png">

### `visualization_main.py`
<img width="999" alt="Screen Shot 2021-10-17 at 1 23 53 PM" src="https://user-images.githubusercontent.com/31188361/137638133-843fee76-ba21-412c-bdc4-5724a43f9f03.png">

**Comment by Emory-NLP** [comment]
Thank you Rafael. Bizarre that  don't get the error. Please add the variable definition in visualization_main and try again. Just to make sure. I am in the middle of other major changes to expedite geocoding so cannot upload now. And the network visualization is not fully connected yet. Cynthia is finishing it up...

def run(inputFilename, inputDir, outputDir, openOutputFiles):
    if Gephi_var==False:
        mb.showwarning("Warning",
                       "No options have been selected.\n\nPlease, select an option to run and try again.")
        return

    filesToOpen=[]

From: Rafael Piloto ***@***.***>
Sent: Sunday, October 17, 2021 1:24 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Visualizations in Gephi (Issue #447)


Describe the bug
Trying to open an SVO output in Gephi via the NLP Suite generates an error.

To Reproduce
Steps to reproduce the behavior:

  1.  Open NLP Suite
  2.  Under visualization tools, go to Network Graphs
  3.  Select the Gephi network graph check box
  4.  See error

Screenshots
[Screen Shot 2021-10-17 at 1 23 35 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F31188361%2F137638121-3015deae-e6d2-4e94-99b4-585f7ddceaa3.png&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729731959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QShMGvKyL5sGEPoz%2BT6MvNJJ8RqOA8TL7DPdiFIr91g%3D&reserved=0>

visualization_main.py

[Screen Shot 2021-10-17 at 1 23 53 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F31188361%2F137638133-843fee76-ba21-412c-bdc4-5724a43f9f03.png&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729731959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6BXkG28QJ67gJtSts42Kr7t6gPM4OA0SKckz0KTv2Mg%3D&reserved=0>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F447&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729741951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tEJjhM0h7Mn89JFR4nfqDiOPZzGNiseoDjpkaaLilPM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q53BD7G5KXJ7TTUD3LTUHMBEZANCNFSM5GFBGMGQ&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729751944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YzPPIwu5yZdROGAi8hEw5mhOUeQ4tdwFAfqb2Bt8d70%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729751944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ydaelLCiiCQ2vEBct7ClmsU4Ym5jFEhSGyfJsg%2BXK5w%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C8840ebbe306e48a8607708d99192fa72%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637700882729761947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EbepLulUa9tb4X8BC9M7PiiQo6BOx9lpy5U12vCnbjA%3D&reserved=0>.

**Comment by RafaelPiloto10** [comment]
Not sure if I am the odd one out, but this appears to be the same case with almost all visualization tools including GIS Google Earth. Since it is still in progress, I don't think it will require too much to look into. I was able to find a work around. The `gxef` file is still generated, so I was able to manually open that in Gephi rather than having it open it up for me automatically
