### ISSUE TITLE
[BUG]: Unable to get Gephi network graphs when running SVO extractor

### ISSUE THREAD

**Issue by ryan-anil** [NLP-Suite/NLP-Suite#451]
I've been using the default setting for the SVO Extraction and have been able to produce the SVO charts and data as well as the Google Earth Pro maps, but I keep getting this error which presumably is stopping Gephi from creating a network graph. Since I have a lot of the output files, is it possible to create the network graph with one of the SVO outputs?
![Screenshot (23)](https://user-images.githubusercontent.com/89484984/137650753-80e93e6f-5e7c-4470-8b9c-17f446e936c3.png)

**Comment by Emory-NLP** [comment]
Ryan, could you upload to issue the complete set of errors you get? The error on line 460 of SVO is not enough. There should be more error lines  in command prompt.

From: ryan-anil ***@***.***>
Sent: Sunday, October 17, 2021 8:30 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: Unable to get Gephi network graphs when running SVO extractor (Issue #451)


I've been using the default setting for the SVO Extraction and have been able to produce the SVO charts and data as well as the Google Earth Pro maps, but I keep getting this error which presumably is stopping Gephi from creating a network graph. Since I have a lot of the output files, is it possible to create the network graph with one of the SVO outputs?
[Screenshot (23)]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89484984%2F137650753-80e93e6f-5e7c-4470-8b9c-17f446e936c3.png&data=04%7C01%7Crfranzo%40emory.edu%7Cb5d5a62812d343af6ace08d991ce7588%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637701138210329280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fVSK%2F2NclvqqzMlzWftvrCZK%2F0qsG6i9TN9HIVXcM5E%3D&reserved=0>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F451&data=04%7C01%7Crfranzo%40emory.edu%7Cb5d5a62812d343af6ace08d991ce7588%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637701138210339276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XH%2FF41hKN7j74qnJ1MOiA2Vhd6FW9w%2FNy%2B8QBZYjLJQ%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q5YANAFZBYYTMTXQ2ZTUHNTBRANCNFSM5GFM6OSA&data=04%7C01%7Crfranzo%40emory.edu%7Cb5d5a62812d343af6ace08d991ce7588%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637701138210339276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w1bBi%2FEsqA7pswtdw9BAxGVyzfTiG7dWZ0n0LdVerts%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Cb5d5a62812d343af6ace08d991ce7588%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637701138210349270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QumDe%2BYO1JJyYbKXQZCos6j0vzWUekVcx1RHUKugfss%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Cb5d5a62812d343af6ace08d991ce7588%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637701138210349270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oVBZ%2BT4sqDcwDw6ixJn2jCatcleoVcIpMsEGm9DHQlU%3D&reserved=0>.

**Comment by ryan-anil** [comment]
That was the only error message I got related to Gephi. When trying to run the Google Earth Pro part of the SVO extraction I get a popup from the NLP Suite which says I need an API key, but still creates the correct output map. This is the command line when I only try to run the Gephi network graphs and leave out the word cloud and Google Earth options.
![Screenshot (25)](https://user-images.githubusercontent.com/89484984/137653329-5dee8aec-73a0-4adc-94a3-d71b6629f677.png)
 
It gets to this point and indicates the number of nodes and edges, but then no output is created using Gephi.
