### ISSUE TITLE
[BUG]: OpenIE annotator stuck in a loop

### ISSUE THREAD

**Issue by austinbeale** [NLP-Suite/NLP-Suite#458]
**Describe the bug**
When I try to run OpenIE on the first Harry Potter book, I get the "Analysis started" popup, which disappears as normal. Then, a few seconds later, another "Analysis started" popup appears, and the same thing happens over and over. I am on version 1.8.4.

**To Reproduce**
1. Open SVO extraction GUI
2. Run "Extract relation triples (via CoreNLP OpenIE)"

**Screenshots**
<img width="1440" alt="Screen Shot 2021-10-20 at 8 27 22 PM" src="https://user-images.githubusercontent.com/92897936/138190783-3a3fcbbe-45b3-45ec-9557-21f69315ec86.png">
<img width="1440" alt="Screen Shot 2021-10-20 at 8 27 04 PM" src="https://user-images.githubusercontent.com/92897936/138190795-50bf5bf1-1625-4aea-a203-3b1cd1cf83c0.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - NLP Suite version 1.8.4

**Comment by Emory-NLP** [comment]
Thank you Austin. Yes, there was a repeated line. Removed. Inconsequential though. Let the script run to the end and it will produce the SVO output.

From: austinbeale ***@***.***>
Sent: Wednesday, October 20, 2021 8:38 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [NLP-Suite/NLP-Suite] [BUG]: OpenIE annotator stuck in a loop (Issue #458)


Describe the bug
When I try to run OpenIE on the first Harry Potter book, I get the "Analysis started" popup, which disappears as normal. Then, a few seconds later, another "Analysis started" popup appears, and the same thing happens over and over. I am on version 1.8.4.

To Reproduce

  1.  Open SVO extraction GUI
  2.  Run "Extract relation triples (via CoreNLP OpenIE)"

Screenshots
[Screen Shot 2021-10-20 at 8 27 22 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F92897936%2F138190783-3a3fcbbe-45b3-45ec-9557-21f69315ec86.png&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780602834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C%2BB9LLf1rocrPQJYbqGtJpRzQWoznrzJWLiFislbiHI%3D&reserved=0>
[Screen Shot 2021-10-20 at 8 27 04 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F92897936%2F138190795-50bf5bf1-1625-4aea-a203-3b1cd1cf83c0.png&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780612826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nZ2Az7cyGcEm7GYolHq7NyTJUAPyMyH3ZOwGHSxVDMU%3D&reserved=0>

Desktop (please complete the following information):

  *   OS: macOS 11.6
  *   NLP Suite version 1.8.4

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F458&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780612826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0UKgQ3oV7kPIPHf2zR%2BhCklVchtrzb4SHU%2Bu%2BgE%2Fp2s%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q55YYCQAVAGDEQE7ORTUH5OF7ANCNFSM5GM4AVSA&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780622827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AM9t20xcT1NewL7Voe0Dkli%2FD%2BxdGym68vbu6an%2B2qY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780632815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NFb6paWoNDMK88ovzSMS5qu3uNZomV8%2BAnUFuv0v3GI%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C34e6400ff7f04dedf66b08d9942b03ca%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637703734780632815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9xYLk7XvY7aOztOcC4e9ev2942k3x3nufgqkxZpDNO4%3D&reserved=0>.
