### ISSUE TITLE
SVO - GIS_KML_util functions VERY slow

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#465]
The functions related to GIS_KML_util are incredibly slow. SVO will extract the SVO quite fast on the seven books of Harry Potter and then grind away for hours in processing pins (GIS_Google_pin_util.pin_customizer). The functions have several For loops and these are VERY slow in Python, particularly in connection to append.

**Comment by Emory-NLP** [comment]
Rewrote the function eliminating two identical for loops but still very slow when processing a very large amount of data.

**Comment by RafaelPiloto10** [comment]
Time Analysis:

<img width="557" alt="Screen Shot 2022-01-21 at 12 56 08 PM" src="https://user-images.githubusercontent.com/31188361/150576687-9b82051a-7565-488d-8955-270d5d4252ad.png">

After running the above time analysis, I was able to pin point that the `BOOT` flag takes on average between 90-120 seconds. This appears to be because of all the nested IO operations occurring after the initial call to: [`GIS_location_util.extract_index()`](https://github.com/NLP-Suite/NLP-Suite/blob/07b3f4056fa1bb36609e8a2f597bedd01af78117/src/GIS_KML_util.py#L95).

Furthermore, the `AVG_LOOP` time (`IF_FOR`) time can be accounted for the call to [`GIS_Google_pin_util.pin_customizer()`](https://github.com/NLP-Suite/NLP-Suite/blob/07b3f4056fa1bb36609e8a2f597bedd01af78117/src/GIS_KML_util.py#L251).

Again, this method appears to continue making the same IO read operations except this is doing it **every iteration**. A 0.02 second iteration is not bad, but it can potentially be faster if we reduce what appears to be redundant IO calls.

**Comment by Emory-NLP** [comment]
That is exactly right! The question: can we eliminate repeated calls and speed up the algorithm?

**Comment by Emory-NLP** [comment]
Wei wonders whether this loop
for j in range(len(data)):
   names.append(data[j][location_num])
can be optimized into 1 call if the data is a panda Dataframe, although unsure whether this change will have a noticeable impact on the performance.
