### ISSUE TITLE
[BUG]: Problem with Step 2 in Re-downloading NLP Suite

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#485]
My laptop was stolen, so I am redownloading the entire NLP Suite on my new laptop, and it's getting stuck after Step 2. 
<img width="560" alt="Screen Shot 2021-10-29 at 1 32 00 AM" src="https://user-images.githubusercontent.com/78457469/139382094-d934765d-1959-494c-9bfd-62216675c9f5.png">
<img width="1440" alt="Screen Shot 2021-10-29 at 1 43 46 AM" src="https://user-images.githubusercontent.com/78457469/139382145-e629c7cc-5359-442d-994d-19fb54f1909a.png">

**Comment by Emory-NLP** [comment]
Oh no! I am sorry Allison! I forwarded this to Wei.

Roberto
Sent from my iPhone

On Oct 29, 2021, at 01:44, allisonreinhardt ***@***.***> wrote:

﻿

My laptop was stolen, so I am redownloading the entire NLP Suite on my new laptop, and it's getting stuck after Step 2.
[Screen Shot 2021-10-29 at 1 32 00 AM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78457469%2F139382094-d934765d-1959-494c-9bfd-62216675c9f5.png&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835111080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1xJkfxrRuMJjjXPoce1q0Z4UyGj8cQiEb%2FIF3xYbl1s%3D&reserved=0>
[Screen Shot 2021-10-29 at 1 43 46 AM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78457469%2F139382145-e629c7cc-5359-442d-994d-19fb54f1909a.png&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835121088%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iDI8QW5Ar1uM2bHTK3NrHlddTpR%2BCxZ5pbK2AsHSPw4%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F485&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835131078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vR3FUwBOIHn0XDwjNIwKfy%2BbBORGhC30h4v94pmtXdI%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56VLVNSUKTDVTTMNGTUJIYEJANCNFSM5G6PW7EQ&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835131078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oQXeXlZgpZrMzRD80XpxHv9EATE13%2B%2FmS6lpxMYJk28%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835141059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kbtQluAp8SLPoGyoND2hEzl0op%2FzojKqLwSGf0kF5Fc%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Cd0ac9921342e4513d6c208d99a9f31d3%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637710830835141059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xBkHeuVziczDq1oftqVS03mBP4LxXtkujPJDSvdqRs0%3D&reserved=0>.

**Comment by DDVD233** [comment]
It looks like STEP1 did not work. Have you ran STEP1? What are the outputs? You can always run it again if you are not sure.

**Comment by allisonreinhardt** [comment]
This is the output for Step 1.
<img width="1315" alt="Screen Shot 2021-10-29 at 10 45 18 AM" src="https://user-images.githubusercontent.com/78457469/139455435-9a433a0c-0272-494e-b26d-a2363d3ef4c3.png">

**Comment by allisonreinhardt** [comment]
After I run Step 1, I see anaconda.sh, but then it disappears when I run Step 2.

**Comment by allisonreinhardt** [comment]
Never mind, I deleted everything and started over, and it worked!

**Comment by Emory-NLP** [comment]
Well... good news (laptop stealing aside :-(

From: allisonreinhardt ***@***.***>
Sent: Friday, October 29, 2021 11:23 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Problem with Step 2 in Re-downloading NLP Suite (Issue #485)


Never mind, I deleted everything and started over, and it worked!

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F485%23issuecomment-954830933&data=04%7C01%7Crfranzo%40emory.edu%7C3d3dbb39b22e4c2f15e508d99af0039e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637711177907705450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C8hlA%2F3fi53%2BCDsbirDxxa%2Fy3s8l4LH8Ux5zvU1xVrA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q576ODWULMNMWVUWQ43UJK35ZANCNFSM5G6PW7EQ&data=04%7C01%7Crfranzo%40emory.edu%7C3d3dbb39b22e4c2f15e508d99af0039e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637711177907715447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jqOKgALuq3sK4i2A8Rj0ZiukB7ixw4Wor1RYvcV7uKE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C3d3dbb39b22e4c2f15e508d99af0039e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637711177907725442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ak4PQlkEQN6m7Obdtv2EuftTfjnCEvH02uECoahh34k%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C3d3dbb39b22e4c2f15e508d99af0039e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637711177907725442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CUwV%2Fk%2FVTyDLbRdFwMBgc4UT%2BGhcbkMnZaTcokxksaE%3D&reserved=0>.

**Comment by Emory-NLP** [comment]
Deleted everything and reinstalled and everything worked.
