### ISSUE TITLE
[BUG]: No Drop-Down Menu for DBpedia and YAGO Ontology Classes

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#487]
**Describe the bug**
When attempting to run the DDBpedia and YAGO tools, there is no drop-down menu option to select ontology classes or subclasses.

**To Reproduce**
1. Open the DBpedia/YAGO annotation GUI
2. Select desired corpus
3. Click the box next to 'ontology class' or 'sub-class'

**Screenshots**
<img width="1104" alt="Screen Shot 2021-10-29 at 11 34 15 AM" src="https://user-images.githubusercontent.com/89608553/139463524-579d04c1-c36c-4775-8a22-f1c9ad032570.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Release Version NLP Release 1.8.9

**Comment by Emory-NLP** [comment]
You say "See error" but there is no error posted. The problem seems to be with the Mac display, different from Windows (where I test). It cuts the Ontology dropdown menu. Try to click inside the widget and see if the options become available. The sub-classes  you need to manually enter (please, read HELP? carefully if you do not want points be deducted). Try that. Do let me know if it works. I have modified the display in the meantime.
![image](https://user-images.githubusercontent.com/79026295/139474207-fe2c4302-2ec7-49f4-bfa9-195006d3e5c3.png)

**Comment by allisonreinhardt** [comment]
I was having this same problem on Mac. Click the Ontology box and then click your down arrow, and it will show you the options. There's just no drop down arrow you can click on because it seems to be hidden under the sub-class field.

**Comment by allisonreinhardt** [comment]
I can't get it to work for the subclasses though.

**Comment by Emory-NLP** [comment]
On a Mac the widget indeed was hidden. Redisegned the layout. Should be visible now.

**Comment by BillyMartin8** [comment]
Great! That solves my issue. Thank you!

**Comment by Emory-NLP** [comment]
Great. Let me know about the question I asked you and Austin.

From: BillyMartin8 ***@***.***>
Sent: Saturday, October 30, 2021 11:33 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: No Drop-Down Menu for DBpedia and YAGO Ontology Classes (Issue #487)


Great! That solves my issue. Thank you!

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F487%23issuecomment-955337282&data=04%7C01%7Crfranzo%40emory.edu%7C4918292df86a4d1ca2c408d99bba9a21%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637712048022495223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fq%2Bo06dixdkw1JsT07OaZJZUMKbVYVZ3KyUxbU9gcy0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56JMAYOPNLVJDWPO2LUJQF37ANCNFSM5G7TURBQ&data=04%7C01%7Crfranzo%40emory.edu%7C4918292df86a4d1ca2c408d99bba9a21%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637712048022505231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R5lHwJ2mZINIHAyvClJNG83h%2F8wrqBH058KIHfQTCpk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C4918292df86a4d1ca2c408d99bba9a21%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637712048022515220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J8eIafBKuX7ET8i0dk7QCG8eyXzW4Ek03Cs2qTlgx8M%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C4918292df86a4d1ca2c408d99bba9a21%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637712048022515220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JNN21MwTERmJVbgmjR67iRo9rMK8gjldJUKqyy4z7I0%3D&reserved=0>.
