### ISSUE TITLE
[BUG]: DBpedia will not run

### ISSUE THREAD

**Issue by saayamorton** [NLP-Suite/NLP-Suite#493]
![image](https://user-images.githubusercontent.com/89603448/139590326-d418bf95-265c-4755-b05e-5b851a6e58dd.png)

After running the DBpedia on my corpus (gay men project) multiple times, it will not continue past this point in the first text file. Am I doing something wrong?

**Comment by saayamorton** [comment]
<img width="1412" alt="Screen Shot 2021-10-31 at 11 55 54 AM" src="https://user-images.githubusercontent.com/89603448/139591820-fed6a7c3-815e-46fc-bed2-83e0d2f7fb05.png">

It also won't let me choose the ontology anymore (the drop down menu disappeared) even though I was able to choose it earlier this morning.

**Comment by Emory-NLP** [comment]
Try 1.9.2

**Comment by saayamorton** [comment]
Thank you!

**Comment by Emory-NLP** [comment]
Saaya, are the problems solved? Otherwise, can we zoom quickly?

**Comment by saayamorton** [comment]
Yes, I was able to run it for one of the ontology categories. The next one I tried timed out but I will try others. The update worked, so thank you so much!

**Comment by Emory-NLP** [comment]
And you can see the drop down menu ok now?

Roberto
Sent from my iPhone

On Oct 31, 2021, at 16:07, Saaya Morton ***@***.***> wrote:

﻿

Yes, I was able to run it for one of the ontology categories. The next one I tried timed out but I will try others. The update worked, so thank you so much!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F493%23issuecomment-955783659&data=04%7C01%7Crfranzo%40emory.edu%7C8ee67d44ce6a42dd78f708d99caa11a0%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713076519144488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0HyqD3yOpQtheCYdeC3LpBlCg%2FqvFAGrFvPJvfBGh7Q%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q52CCVZAVEMOAYER56LUJWOYFANCNFSM5HCNZXQA&data=04%7C01%7Crfranzo%40emory.edu%7C8ee67d44ce6a42dd78f708d99caa11a0%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713076519154479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GoDVqFJHt8Qvl8o39GQ3yR5Dp%2BNAmnnnEsklrJT9EVc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C8ee67d44ce6a42dd78f708d99caa11a0%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713076519154479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c87BtkWY9iArTrijKYrCDr%2FGV%2FpFK2hQ0nJ%2FTHX3Ams%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C8ee67d44ce6a42dd78f708d99caa11a0%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713076519164473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=irhHVn668PIxMJcZppoZEJI2AQd%2FbHMcaM88qipZAqQ%3D&reserved=0>.

**Comment by saayamorton** [comment]
yep! One of my friends with a Mac showed me that you just have to click the down arrow on the keyboard and the menu shows up.

**Comment by Emory-NLP** [comment]
Do you have time to zoom so that I can fix the width for a Mac?

Roberto
Sent from my iPhone

On Oct 31, 2021, at 16:13, Saaya Morton ***@***.***> wrote:

﻿

yep! One of my friends with a Mac showed me that you just have to click the down arrow on the keyboard and the menu shows up.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F493%23issuecomment-955784521&data=04%7C01%7Crfranzo%40emory.edu%7Ce992ef78768b4de58b2208d99caaf43e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713080338595402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wHTfQ2YNqT6iEKM7qaYPb1qCdW9em20WOCZ%2BN1p7A7M%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q56NL744VWXV4XOK4ITUJWPP3ANCNFSM5HCNZXQA&data=04%7C01%7Crfranzo%40emory.edu%7Ce992ef78768b4de58b2208d99caaf43e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713080338605397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zGxxL1qi0gNK3lG0WXZzPNL%2Fn2pnenEpOu05Qzhex%2Bw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7Ce992ef78768b4de58b2208d99caaf43e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713080338605397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PuHDCIdFt%2BK198NO5y%2FFtQ9ABR3eWv37RjHu3y548dE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7Ce992ef78768b4de58b2208d99caaf43e%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713080338615391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OPzux%2B9doC1FG0ul8qfGX1HABGgHV9rd6mWpCHS9ZfA%3D&reserved=0>.

**Comment by saayamorton** [comment]
Yes I can! Should I join the office hours link?

**Comment by Emory-NLP** [comment]
Yes thank you!

Roberto
Sent from my iPhone

On Oct 31, 2021, at 16:16, Saaya Morton ***@***.***> wrote:

﻿

Yes I can! Should I join the office hours link?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F493%23issuecomment-955784852&data=04%7C01%7Crfranzo%40emory.edu%7C40569838013948158ba608d99cab5acd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713082047270263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NoETNbULoMCstNL6DoJAaQw%2FJmGJhdT8OMUQ1QD5tL0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q55K7FBR7DTI36LW7VLUJWP2VANCNFSM5HCNZXQA&data=04%7C01%7Crfranzo%40emory.edu%7C40569838013948158ba608d99cab5acd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713082047280258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=clwE3zfYYh86to5FxyCCJfBzZfkCOdEMPks3%2Fit3RD4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C40569838013948158ba608d99cab5acd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713082047280258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SZGhodQgk3JS%2FGqk0C9G3tkdWho%2Bos2t%2FvRDkZIfyaw%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C40569838013948158ba608d99cab5acd%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637713082047290255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sffWoOpzeFgbC24KqGp5XhxuBhhhZA0OB0K96DGc%2BoM%3D&reserved=0>.
