### ISSUE TITLE
[BUG]: Issue with automatic updating NLP Suite 

### ISSUE THREAD

**Issue by Joshman7177** [NLP-Suite/NLP-Suite#759]
I get a notification to update that says it will automatically be updated to the newest version the next time I boot up the Suite. When I close down the suite I get a notification saying my NLP suite has been successfully update. Then, when I open the Suite back up I am still running the old version and get the same notification saying it will be updated the next time I run it.

**Comment by Emory-NLP** [comment]
Please, do come see me so that we can take a look at what is happening with your code.

**Comment by DDVD233** [comment]
It would be helpful if you could screenshot the terminal/command line window and post it here.

**Comment by Emory-NLP** [comment]
The problem is that pygit2 was not installed. Please, pip install pygit2. Since pygit2 is automatically installed by requirements.txt, something may have gone wrong. So, let's run the requirements. Open command line/prompt type NLP to be in the right environment and src folder. Type CD .. and type pip install -r requirements.txt This will take some time to excecute but it should solve your problems.  Samir just got his to update correctly after doing this.
