### ISSUE TITLE
[BUG]: Gephi asks you choose files and IT EXITS

### ISSUE THREAD

**Issue by HelenBai2002Tong** [NLP-Suite/NLP-Suite#910]
Selecting Gephi and clicking run, it asks you to select a .csv file but exits after clicking on OK
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/38171691/199845928-90e95a4e-5cb4-4009-b9cc-03a335663ac0.png">

System: MacOS

**Comment by Emory-NLP** [comment]
Since I cannot see which option you are selecting in the NLP_menu_main GUI, I assume you are selecting the visualization option which, as you can see does not result in the error you get. I have, however, improved the user-interaction for network graphs. 
![image](https://user-images.githubusercontent.com/79026295/199957363-d3eccda3-aa0f-4cc1-88d7-5a6152d5747b.png)
